### ISSUE TITLE
Add nodecov to list of terms supported by dissolution_coefs

### ISSUE THREAD

**Issue by sgoodreau** [EpiModel/EpiModel#322]
I need this for a model I'm going to run for Evonet, so might as well add it for all to use.  Will create a branch and then merge back.

**Comment by smjenness** [comment]
@sgoodreau : have there been any advances on this, even in bespoke project code with EvoNet?

**Comment by sgoodreau** [comment]
@smjenness Nope, sorry. I ended up not needing it for Evonet and used nodefactor instead. @chad-klumb I think this would be an easy and quick task for you.  Could you take a stab?

**Comment by martinamorris** [comment]
Actually, it is a problem.  AFAIK, nodefactor actually doesn't work -- only nodematch does.  We had this discussion a month or so ago when I was hoping to use nodefactor(age) for a hetdiss model.  The issue is that the attributes of both nodes needs to be considered.  For nodematch, it's unambiguous how to calculate the target mean rel age values.  But for nodefactor/cov, it's not so clear.  I think both SMG and I have had discussions with @krivit about this.  His take is that it may be possible, but it's not obvious how to do it.

**Comment by chad-klumb** [comment]
Given the sort of information passed to `dissolution_coefs`, I can imagine `nodefactor` being used to target durations for "pure" ties `A-A`, `B-B`, etc., with "mixed" ties `A-B` being halfway in between the corresponding pure ties on the log odds of persistence scale.  I would have to check to be sure this is what it's actually doing, but it's the only generally tractable use of `nodefactor` that I can imagine, with just the target durations passed.  (Targeting mean durations of half-edges based on attribute type would not be doable, in general.)

**Comment by martinamorris** [comment]
That makes some sense from an abstract perspective.   But for age (for example) there's a hard limit imposed on relage for young persons who partner with older persons.  It's a constraint really.

In any case it would be a departure from our current approach, which uses the empirical estimates of mean relage as the basis for the `disscoef` calculations.

I'm wondering if @smjenness's approach of using models to fit/predict values to construct target stats might be a somewhat principled way to proceed.  So, some kind of model like the following, fit on the edges:

```
relage = b0+ b1_i(nodefactor1) + b2_j(nodefactor2) + b3_ij(nodematch, diff=T)  where i, j are levels of nodefactor
```
{note, fit with a constant, the nodematch term for the omitted level would be aliased}

Ideally the estimates b1=b2 for the same levels, and b3 indicates if the effects are additive or interactive (and it could be fit as uniform homophily).  This still doesn't address the age constraint issue I mentioned above.

But what I don't understand well enough is the underlying statistical theory that @krivit has in mind when he is thinking through whether this term is estimable.

**Comment by sgoodreau** [comment]
Thanks @martinamorris , for reminding me (again) that this isn't just a simple issue of adding a few lines of code.  As long as nobody in our group needs it for a specific model anytime soon, I would keep this low on the list of things to work on.  Especially since nodemix can generally do the trick. But yeah, if you were going down this route, then presumably you'd need to estimate the model in line with the fact that the log odds of persistence will be additive in the thetas for each of the two nodes' attribute values. Once you get into interaction effects, you might as well use nodemix.

**Comment by sgoodreau** [comment]
Now that we're removing `nodefactor`, we shouldn't be turning around and adding `nodecov`!  I don't even remember now what my original use case was for this but it's long since passed.
