### ISSUE TITLE
edge duration plots from netsim objects

### ISSUE THREAD

**Issue by martinamorris** [EpiModel/EpiModel#457]
It looks like the only options are type="formation", "network","epi"

Would it be difficult to add "duration" for edge duration plots (like the ones from netdx)?

**Comment by smjenness** [comment]
Not currently, but I agree this would be relatively easy to add

**Comment by martinamorris** [comment]
Would be very helpful.  In general, it would be helpful to have all of the dx available in netdx (which are "pre-epi" sims) available for diagnosing the epidemic sim runs, after you add any demographic dynamics and epi-related feedback effects.

**Comment by chad-klumb** [comment]
It looks like `netdx` essentially calculates the same thing as the `mean.age` term, but utilizes the function `edgelist_meanage` to do so.

I've been considering adding durational information tracking to `tergmLite`; if that were done, we'd be able to use durational terms (such as `mean.age`) in the `monitors` argument during `tergmLite` epidemic simulation.

In `tergm 3.6` the `lasttoggle` data structure (used for durational information tracking) was basically the size of an adjacency matrix, making it unsuitable for large networks.  In `tergm 4.0` it's much lighter, and I've used it with networks up to 800k nodes with no problem.

**Comment by martinamorris** [comment]
Nice.  We'll want flexibility here to monitor heterogeneous dissolution models specifically, where `mean.age` will be broken down by attributes (node or tie).

**Comment by smjenness** [comment]
@chad-klumb if this is added to tergmLite, let's please make sure to do benchmarking to make sure this does not slow anything down

**Comment by martinamorris** [comment]
@smjenness it needs to be an option, in any case, because we need it to be able to diagnose durations in simulations.

**Comment by chad-klumb** [comment]
Okay.  I've previously considered extending `mean.age` so it can take a vertex attribute and give statistics that are stratified by mixing type on that attribute; it sounds like that would be useful here as well.

We can make the durational information tracking optional (with no tracking being the default) if there are performance concerns.

**Comment by chad-klumb** [comment]
closed by #702
