### ISSUE TITLE
General overhaul of heterogeneous dissolution model code

### ISSUE THREAD

**Issue by martinamorris** [EpiModel/EpiModel#459]
The het diss model code and utilities are sorely in need of some love.  Now that I'm using a het diss model, I'm finding lots of issues that make these models both fragile (to specify) and opaque (in terms of built-in diagnostics).  So I'll list these issues here as I find them.
 
1. There is an implicit expectation in `netest.R` that the formation model coefs are in the same order as the dissolution model coefs:

https://github.com/statnet/EpiModel/blob/3434981d1359ba4a4de0a02c546b1003af54209c/R/netest.R#L199-L202

I don't see a check that enforces this, or throws a warning if it is not true.  It would be good to have one.

2. The examples talk about a node factor, age.grp, but use the nodematch term in the model:

https://github.com/statnet/EpiModel/blob/03ac578f40015e50ffd110b0ebb6e1fc76d3e0d0/R/net.utils.R#L288-L306

This avoids the thorny problem of specifying the mean age of the ties by nodefactor(age.grp), since both nodes have (potentially different) values of age.grp, so it is probably the right choice for a simple example.  But ...

* It would be good to adjust the text in this example so it is explicit that we we are doing this (and why?).  

* Since `nodefactor` is a term we allow in het diss models, we should have an example of how to deal with this, somewhere.

3. We should be able to offer a couple more terms.

It's not clear why we can't also allow people to use some other simple ergm.terms, like `concurrent`  or `deg(1)` that are frequent flyers in our formation models, and good candidates for dissolution effects.  Both add a single statistic, and, the mean age of ties for the targetstat group are easy to calculate.

4. The netdx utilities have not been built out for het diss models.

```
> print(dx)
EpiModel Network Diagnostics
=======================
Diagnostic Method: Dynamic
Simulations: 5
Time Steps per Sim: 1000

Formation Diagnostics
----------------------- 

Dissolution Diagnostics
----------------------- 
----------------------- 
* Heterogeneous dissolution model results averaged over
```
Last line (which is a bit terse) indicates we can't dx the individual het diss fits, just the overall.

```
> plot(dx, type = "duration")
Error: Duration plots for heterogeneous dissolution models not currently available
```
And we can't even get the overall plots.

Once these issues are addressed, it would be helpful to have a vignette showing how to use all of this in practice.

**Comment by smjenness** [comment]
@martinamorris : thanks, please feel free to assign someone from your group to work on this.

**Comment by smjenness** [comment]
cc'ing @sgoodreau specifically to comment on issue 3 above.

**Comment by chad-klumb** [comment]
Exactly what mean durations would we be passing to `dissolution_coefs` when using node-level dissolution terms like `nodefactor`, `concurrent`, and `degree`?

**Comment by martinamorris** [comment]
That's a good question, as with any node-level level dissolution term (includes `nodefactor`).

And I'm not sure what the answer is.  

If it parallels the construction of the target stats themselves,  each node in a tie would contribute a (possibly weighted) value to the aggregate term.  But let's talk.

**Comment by smjenness** [comment]
@sgoodreau worked on this problem before. These are not analytically tractable.

**Comment by martinamorris** [comment]
@smjenness can you be more specific?  Pavel had a concurrent term in the dissolution model of his dissertation, and it worked.

**Comment by smjenness** [comment]
was Pavel's dissertation model longitudinal (panel) census network data?

**Comment by martinamorris** [comment]
> was Pavel's dissertation model longitudinal (panel) census network data?

not as i recall.  he used the NHSLS throughout.

**Comment by smjenness** [comment]
ok, @sgoodreau can comment further about challenges in calculating these dyad-dependent terms as offsets

**Comment by sgoodreau** [comment]
Moving into other dissolution models gets complicated very quickly. Other dyadic independent models besides nodemix can surely be done, but they aren't straightforward in terms of what is being specified and how the two members come together to create the durations (or, really, the log-odds of persistence), and how that relates to the kinds of data we have.  If @martinamorris wants to tackle this I think it's great, but I predict it will be more work than it initially seems.

As for dyadic dependent dissolutions, my understanding was that it was intractable under current methods. I don't know what Pavel did i his diss, but we should surely check more deeply and see.  Even if doable, it would require a pretty major restructuring of our method and codes.

**Comment by sgoodreau** [comment]
@smjenness Would you like me to tackle adding het diss models to print.netdx and plot.netdx next?  That's not quite what this issue is asking for, but it is low-hanging fruit now that I've dived into the relevant code.  If so, I'll open a new issue.

**Comment by smjenness** [comment]
@sgoodreau yes, that would be great! If you would like to open up other related but more specific issues to track the work, feel free.

**Comment by sgoodreau** [comment]
I'm closing this issue because it contains at least different sub-issues, which are now each in different states:

1) adding printing/plotting for heterogeneous dissolution models: DONE as of today
2) updating error checking across the formation and dissolution models: superceded by #684, which will make this whole system more robust and flexible
3) adding in more complex dissolution models like concurrent: much bigger task, which would require us to redo the whole dissolution modeling approach in EpiModel, as this currently relies on closed-form solutions and not ergms.  If @martinamorris or anyone else wants to pursue this, they can open a fresh issue on this specifically. As per conversation above, checking exdactly what Pavel did in his diss, and seeing if it is integratable into EpiModel, is a key first step.

**Comment by smjenness** [comment]
Sounds great, thanks @sgoodreau. Exciting to see all these issues, some several years old, closed!
