### ISSUE TITLE
Support for edge covariates in networkLite methods

### ISSUE THREAD

**Issue by ThomasKraft** [EpiModel/EpiModel#495]
I am experiencing unexpected behavior with netsim when trying to update an edge covariate during the course of a simulation. To test what was going on, I created a simple module that sets my edge covariate variable to NULL during the simulation, with the expectation that an error would be thrown. The following MWE illustrates this exactly:
```
library(EpiModel)
toy <- network_initialize(n=20, directed=F)

# create matrix for edgecov term
ec <- matrix(sample(seq(0,.5, .1), 400, replace=T),20)
ec[lower.tri(ec)] = t(ec)[lower.tri(ec)]  # make the attribute matrix symmetric
diag(ec) <- 0

fit_test <- netest(toy, 
                   formation = ~edges + edgecov(ec) , 
                   target.stats = c(30, 10), 
                   coef.diss = dissolution_coefs(dissolution = ~offset(edges), duration = 20), edapprox = T) 

check_fun <- function(dat, at) {
  if(at > 2){
    ec <- NULL
  } 
return(dat)
}
  
param <- param.net(inf.prob = 0.3, act.rate = 1)
init <- init.net(i.num = 5, r.num = 0)
control <- control.net(type = NULL, nsteps = 20, nsims = 1, ncores = 1,
                       check_fun.FUN = check_fun)
sim <- netsim(fit_test, param, init, control)
``` 
This is a problem for me because it suggests that manipulations that I am doing to the `ec` variable within modules are not actually influencing the model, and instead suggests that whatever `ec` is in the environment when I start `netsim` is getting used throughout. This seems like a bug unless there is another way to access edge covariates dynamically (as can be done to vertex attributes within `dat`).

**Comment by ThomasKraft** [comment]
UPDATE: I can produce the expected error if I set the edge covariate as a network attribute, and then use `delete.network.attribute` in my checking module (see updated MWE below). Presumably this means I can modify the network attribute dynamically to produce desired changes using `set.network attribute`, but then I don't see how this can be accomplished when using tergmLite and there is no actual network object to manipulate. Unless tergmLite has a unique way of storing edge covariates?

```
toy <- network_initialize(n=20, directed=F)

# create matrix for edgecov term
ec <- matrix(sample(seq(0,.5, .1), 400, replace=T),20)
ec[lower.tri(ec)] = t(ec)[lower.tri(ec)]  # make the attribute matrix symmetric
diag(ec) <- 0

toy %n% "ec" <- ec
ec <- NULL
toy %v% "race" <- rep(c("a", "b", each=10))

fit_test <- netest(toy, 
                   formation = ~edges + nodefactor("race") + edgecov("ec") , 
                   target.stats = c(30, 15, 15, 10), 
                   coef.diss = dissolution_coefs(dissolution = ~offset(edges), duration = 20), edapprox = T) 


check_fun <- function(dat, at) {

  if(at == 2){
    ec <- NULL
    toy %n% "ec" <- NULL   #makes no difference
    dat$nw[[1]] <- delete.network.attribute(dat$nw[[1]], "ec") # causes expected error
    #dat$nw[[1]] <- delete.vertex.attribute(dat$nw[[1]], "race") # causes expected error
  }
return(dat)
}
  
param <- param.net(inf.prob = 0.3, act.rate = 1)
init <- init.net(i.num = 5, r.num = 0)
control <- control.net(type = NULL, nsteps = 20, nsims = 1, ncores = 1,
                       check_fun.FUN = check_fun,
                       resimulate.network = T)
sim <- netsim(fit_test, param, init, control)
```

**Comment by ThomasKraft** [comment]
UPDATE2: It seems possible that I got ahead of myself, as further tests indicate that `edgecov` terms are not supported for tergmLite?

**Comment by smjenness** [comment]
Yes, that's correct - use of edge covariates is not supported for tergmLite.

**Comment by ThomasKraft** [comment]
@smjenness I'm guessing it's not the simple, but wouldn't it be possible in `init_tergmLite` to call `get.edge.attribute.list` on the network object, and then save a list object into `dat` containing any edge attributes (around here https://github.com/statnet/tergmLite/blob/3f006d539e9f9b02bb7d1c8a7ab1645c179c14ce/R/initialize.R#L178)? Then the simulate function could find those attributes within `dat` the same as it does for vertex attributes.

Also just for clarity -- is it not surprising in the first example above that setting `ec` to NULL during simulations fails to throw an error?

**Comment by smjenness** [comment]
Regarding support for edge attributes, your suggestion may be a good starting point. If you'd like, please feel free to file a Github issue that contains this feature request over on https://github.com/statnet/tergmLite. We do not have the capacity to implement this currently, but we can consider it for the future.

I am not sure about the error in the example above. Perhaps @chad-klumb or @AdrienLeGuillou have insights there?

**Comment by chad-klumb** [comment]
This functionality should now be available, provided it is invoked properly.

Currently network attributes in `tergmLite` simulation are stored as `attr`-style attributes on the edgelist.

This means that to update the `"ec"` network attribute during `tergmLite` simulation you want to update `attr(dat$el[[1]], "ec")`.

e.g., from the test in #650,

https://github.com/EpiModel/EpiModel/blob/15e9d628bcb5b3dbb03672baaa3d7e3faea07f59/tests/testthat/test-net-tergmLite.R#L241-L246

The point of the `+/-Infs` in the test is to make it clear that we're using the intended value for `"ec"` by verifying that we get a complete/empty network at the corresponding time step.

**Comment by chad-klumb** [comment]
In the future it might be nice to have a `dat` field for network attributes, much as `dat$attr` currently stores vertex attributes.

**Comment by ThomasKraft** [comment]
@chad-klumb this looks fantastic, thanks! Could you clarify the following:

1. What accounts for the `at == 3` part of `m <- matrix(if(at == 3) +Inf else -Inf, n, n)*coefsign`? Does this check not need to be performed at other steps? 
2. If I use custom modules to modify the edge covariate `ec` dynamically throughout simulations, would this be a reason to implement that step at other timesteps?

**Comment by chad-klumb** [comment]
In general you may update `ec` at all time steps, and the logic for performing the updates (including the exact numerical values used in the `ec` matrix) will depend on your particular application.  The test simulation uses only 4 time steps, and the behavior of `ec` is to be "normal" for the first time step, `-Inf` for the second and fourth timesteps, and `+Inf` for the third timestep.  The reason for the infinities is purely for testing purposes, so that it's easy to verify (by checking network edgecount) that we are getting the updated `ec` on each time step.

**Comment by smjenness** [comment]
@chad-klumb : wow, that is excellent news. Thanks for demonstrating this. I will merge in #650 and close this issue.
