### ISSUE TITLE
delete_attr, deleteAttr and nodes removal in general

### ISSUE THREAD

**Issue by AdrienLeGuillou** [EpiModel/EpiModel#598]
In R/utils.R their is two functions to delete the attributes of removed nodes:

- `deleteAttr`: that received the attribute list and output the updated version to be stored back in `dat`
- `delete_attr`: which receives a `dat` object and update it

the former is used in EpiModelHIV and EpiModelCOVID but the latter would be more coherent with then new APIs as it uses the same logic of:

```
dat <- some_modifier(dat)
```
Overall, it may be desirable to have a simple wrapper function to handle the deletion of nodes.

In EpiModelHIV we currently delete nodes with this code:

```
  if (length(idsDepAll) > 0) {
    dat <- set_attr(dat, "active", 0, posit_ids = idsDepAll)
    for (i in 1:3) {
      dat[["el"]][[i]] <- delete_vertices(
        dat[["el"]][[i]],
        idsDepAll
      )
    }
    dat[["attr"]] <- deleteAttr(dat[["attr"]], idsDepAll)
    attr.length <- unique(vapply(dat[["attr"]], length, numeric(1)))
    if (attr.length != attributes(dat[["el"]][[1]])[["n"]]) {
      stop("mismatch between el and attr length in departures mod")
    }
  }
```

we could have a function in EpiModel of the form

```
dat <- delete_nodes(dat, departure_posit_ids)
```

that would handle all the housekeeping in a consistent manner over all the projects.

**Comment by chad-klumb** [comment]
I'll volunteer to implement this and apply it to EpiModel@main, EpiModelHIV-p@dev, and EpiModelCOVID.

**Comment by AdrienLeGuillou** [comment]
superseeded by #846
