### ISSUE TITLE
Add alternative parameterization for resimulation.networks to allow for ranges

### ISSUE THREAD

**Issue by smjenness** [EpiModel/EpiModel#606]
This has come up in the new CEA example in the EpiModel Gallery by @gknowlt. We need to stop the network resimulation at a specific time step to allow for other dynamic processes to accrue in the absence of ongoing ID exposure. I am thinking this would involve inputting a vector of time steps to control.net's resimulate.network, where the current approach is just TRUE or FALSE. If the vector < nsteps in control.net, then the resimulate.net module would get skipped. I'll ask @AdrienLeGuillou to work on this and @gknowlt to check it against the gallery example when done.

**Comment by AdrienLeGuillou** [comment]
Changing `resimulate.network` from a `logical(1)` to a `numeric(n)` or a `logical(nstep)` will probably have some side effects in other functions as this control is used multiple times in the core modules and a `logical(1)` is always expected.

I think we should change the value of `control$resimulate.network` to `FALSE` when the model does not need to be resimulated so all functionalities linked to the simulation would be disabled as well.

To do so multiple approaches are possible:

1. a new `control` that would switch it on and off
2. extending the `updater` module so it would also be able to modify `controls` at given time steps 

The implementation of the second solution would be very quick as the module already exists and works for parameters. Making it work with controls would require little coding. I like this approach as it would provide a consistent interface for changes that should occur during the simulation.

What do you think?

**Comment by smjenness** [comment]
@AdrienLeGuillou : I agree, 2 makes more sense. Does the new updater API also work for control settings (I know it works for params but unsure about controls). Could you take a look at the CEA gallery example and see what it would take to update that example?

**Comment by AdrienLeGuillou** [comment]
The API does not work for controls yet but I can change that by simply adding a `control.updater.list` in `control` similar to  `param.updater.list` in `param`. 

The module itself would use the same logic and simply look at this new list for `control` updates.

The implementation in CEA would be trivial with this update. I already have a working version on this example locally so I can use it to test this new variation.
