### ISSUE TITLE
Error with netdx

### ISSUE THREAD

**Issue by thednainus** [EpiModel/EpiModel#615]
Hello,

Why sometimes I get the following error message with `netdx`?
_Error in tergm_MCMC_slave(state, eta.comb, control, verbose) : 
MCMCDyn failed with error code 3_

It seems to happen when analysing large networks.

**For example: Using the example in the EpiModel package as explained below:**

```
# Network initialization and model parameterization
nw <- network_initialize(n = 40000) # the example in the package uses n = 100
formation <- ~edges
target.stats <- 20000 # the example in the package uses 50 (so I kept the the same proportion here (not sure whether it is correct)

coef.diss <- dissolution_coefs(dissolution = ~ offset(edges), duration = 25)

# Estimate the model
est <- netest(nw, formation, target.stats, coef.diss, verbose = FALSE)

# the function netdx works fine here
# Dynamic diagnostics on the STERGM approximation
dx2 <- netdx(est,
             nsims = 5, nsteps = 500,
             nwstats.formula = ~ edges + meandeg + concurrent,
             set.control.ergm = control.simulate.ergm(MCMC.burnin = 1e6)
)
```
However, If I change the value of nsteps to 1000, I get the same error message in my computer (_Error in tergm_MCMC_slave(state, eta.comb, control, verbose) : 
MCMCDyn failed with error code 3_)

```
# Dynamic diagnostics on the STERGM approximation
dx2 <- netdx(est,
             nsims = 5, nsteps = 1000,
             nwstats.formula = ~ edges + meandeg + concurrent,
             set.control.ergm = control.simulate.ergm(MCMC.burnin = 1e6)
)
```

**Comment by chad-klumb** [comment]
Looks like the maximum allowed number of changes needs to be increased.

Can you try passing `set.control.stergm = control.simulate.network(MCMC.maxchanges = 1e7)`?

**Comment by thednainus** [comment]
Thanks! Adding this option did work.
