### ISSUE TITLE
Use of all.equal in package -- CRAN update required

### ISSUE THREAD

**Issue by smjenness** [EpiModel/EpiModel#622]
Message from CRAN:

> This is documented as
> 
>       all.equal(target, current, ...)
> 
>       ## S3 method for class 'numeric'
>       all.equal(target, current,
>                 tolerance = sqrt(.Machine$double.eps), scale = NULL,
>                 countEQ = FALSE,
>                 formatFUN = function(err, what) format(err),
>                 ..., check.attributes = TRUE)
> 
> Packages
> 
>    EpiModel MetricsWeighted PLNmodels actuar clustermq estimatr lme4
>    nvmix optimall qgcomp rockchalk sensR univariateML updog ursa
> 
> (and others reported separately) call it with three unnamed arguments, 
> the first of which is numeric so the third gets matched to 'tolerance'. 
>   As NEWS for R-devel says
> 
>      • all.equal.numeric() gains a sanity check on its tolerance
>        argument - calling all.equal(a, b, c) for three numeric vectors
>        is a surprisingly common error.
> 
> See the package's CRAN results page for the details of the check failure 
> (for Fedora now, others will follow).
> 
> Please correct before 2022-02-06 to safely retain your package on CRAN.
> 
> -- 
> Brian D. Ripley,                  ripley@stats.ox.ac.uk
> Emeritus Professor of Applied Statistics, University of Oxford

**Comment by AdrienLeGuillou** [comment]
fixed by #623 

If I understand correctly, only the use of `all.equal` with 3 unnamed arguments is a problem. 
There are still 2 other use of `all.equal` in "merge.R" lines 189 and 190. But they should not be a problem.
