### ISSUE TITLE
Consistency for truncation parameters for cumulative edgelists

### ISSUE THREAD

**Issue by smjenness** [EpiModel/EpiModel#628]
@AdrienLeGuillou The `update_cumulative_edgelist` function uses `truncate` whereas `get_partners` uses `max.age`. I think `truncate` the better parameter name for both, as age is not the right term for partnerships that have already ended (we don't keep incrementing a person's age after they have deceased). I can make this switch easily but want to check with you about related vignettes and extension packages that use `get_partners`. I would like to push this out for v2.2.1 because it involves a breaking change for a new argument name.

**Comment by AdrienLeGuillou** [comment]
I agree, `truncate` would work here as well and is more consistent. If we are changing this, I would also like to change the `only.active` parameter to `only.active.nodes` or something that reflect the fact that we are talking about the nodes being active in the network and not the partnerships being still ongoing. If you have a better name I am all for it

**Comment by smjenness** [comment]
Ok, let's go for it. I agree with the change of the other parameter too.

**Comment by smjenness** [comment]
Please prioritize for Monday/Tuesday this week if possible so I can push out EpiModel mid week. Thanks!

**Comment by smjenness** [comment]
Closed with #630
