### ISSUE TITLE
Documentation for certain functions needs review 

### ISSUE THREAD

**Issue by karina-d-wallrafen** [EpiModel/EpiModel#633]
- [x] param_random (net.inputs.R):
The description of the output ("one of the values from the values vector") seems inaccurate

- [x] generate_random_params (net.inputs.R):
The documentation mentions both a "random_params" argument and a "random.params" argument. Are they supposed to be the same? The second sentence in the random_params section ("...param_random is a function factory provided by EpiModel for act.rate and tx.halt.part.prob we provide bespoke functions") is confusing

- [x] netest / update_dissolution (netest.R):
The description for the nested.edapprox argument is confusing

- [x] absdiffby / absdiffnodemix (ErgmTerms.R):
For absdiffby, the second sentence in the Details section ("The absdiff component targets age-based homophily while the by component allows that to be structed by a binary attribute...") may need to be rephrased. These functions are both listed twice in the index of help pages (once as absdiffby / absdiffnodemix and once as InitErgmTerm.absdiffby / InitErgmTerm.absdiffnodemix) 

- [x] control.dcm (dcm.inputs.R): 
From the description, it is unclear what happens when sens.param is set to FALSE but there are parameters with length > 1

- [x] get_network_term_attr (net.utils.R):
The title ("Outputs ERGM Formula Attributes into a Character Vector") seems to have been copied from the documentation for get_formula_term_attr and may need to be adjusted

- [x] control.net (net.inputs.R):
The last sentence in the description for tergmLite.track.duration ("...lasttoggle defaulting to all lasttoggle times unspecified...") is confusing

- [x] record_attr_history / record_raw_object (net.record.R):
The given examples cannot be run in isolation (and from the description it isn't clear how they should be used). The function description for record_attr_history says "nodes are identified by their unique_ids," but the function seems to use posit ids instead

**Comment by AdrienLeGuillou** [comment]
thank you so much @karina-d-wallrafen  for your in depth review of the comments! 
That's super useful

@smjenness and @karina-d-wallrafen: I think we should try to have a single definition for `dat` as an input parameter and the return of functions and use `inheritParams` and `inherit <fn> return` everywhere. This would allow  us to modify them in one place when required and ensure perfect consistency all over the code.
