### ISSUE TITLE
Allow param.net to receive a formatted `data.frame` of parameters

### ISSUE THREAD

**Issue by AdrienLeGuillou** [EpiModel/EpiModel#641]
add a new parameter to `param.net` to use a formatted `data.frame` of parameters.

The `data.frame` will need to contain at least the 3 following columns:
1. 'param': the name of the parameter. If it is a multi dimension parameter, prepend the name, with "_1", "_2", etc for the position in the vector.
2. 'value': the value for the parameter (or the Nth position if  multidimensional) 
4. 'type': a character string containing either "numeric", "logical" or "character". The type the value will be cast to.

If a parameter is defined twice (in the `data.frame` and as a normal argument), a WARNING will be produced and the value actually used will be displayed for the user. @smjenness, which value should be used? The one from the DF or from the argument to `param.net`

**Comment by smjenness** [comment]
Closed with #642
