### ISSUE TITLE
Deprecate nodefactor in dissolution models

### ISSUE THREAD

**Issue by sgoodreau** [EpiModel/EpiModel#647]
It doesn't have the desired behavior, and getting it to have that behavior is a surprisingly tricky undertaking.  Users can always use the more general `nodemix` instead.

**Comment by sgoodreau** [comment]
@smjenness Remind me: we decided to remove this totally in the next release, right?  As opposed to sending a deprecation message in the next release, and then removing it in the one after that?

**Comment by smjenness** [comment]
The latter: deprecation first (for a while), and then eventual removal. While it is hard to imagine anyone is using nodefactor dissolution terms (perhaps it is important for equine herpes models?), we should avoid unexplained breaking changes when possible. When you write the deprecation message, please put in the comments: `# TODO: remove deprecation message in future release` or something like that, but tagged with `TODO` (so I can find it). Thanks!

**Comment by sgoodreau** [comment]
Conpleted with a series of commits in the netdx_heterodiss branch.  Will file a new issue now to remove in a later version.
