### ISSUE TITLE
y-lim min and max values reversed?

### ISSUE THREAD

**Issue by sgoodreau** [EpiModel/EpiModel#655]
Variations on the following code appear a few ties in 'plot.netdx' (and perhaps in other plotting functions):

```
qnt.min <- 1E10
qnt.max <- -1E10
mean.min <- 1E10
mean.max <- -1E10
```

Based on the names, it would seem that the mins should be the negative ones and the maxes the positive ones.

Practical impact is likely low, since these are mostly intended as place holders until actual values are calculated.  But if they're in there, then it's still worth getting them logically right.

**Comment by smjenness** [comment]
Quite a few places where these were reversed. Hard to imagine these were all typos. @AdrienLeGuillou could you take a look as time permits?

https://github.com/EpiModel/EpiModel/blob/main/R/plot.R#L649-L653

**Comment by AdrienLeGuillou** [comment]
I am not super familiar with the `plot.netsim` function or with the `base R` plotting system but from from what I understand

```
qnt.min <- 1E10
qnt.max <- -1E10
mean.min <- 1E10
mean.max <- -1E10
```

is just here to give placeholder values before `draw_qnts` and `draw_means`. 
I guess it was put here to ensure that numerical values are returned and not `NA`s when calling `min(qnt.min)` and `max(qnt.max)`. I suppose they were set to such small values to avoid overriding the real values in the normal case.

**Comment by smjenness** [comment]
@AdrienLeGuillou : that's right. Could you reverse these signs, such that the max is 1E10 and min is -1E10 and test against some plots to see that this does not break anything? Unfortunately, unit testing for plots is not much more sophisticated than that!

**Comment by AdrienLeGuillou** [comment]
@smjenness : I could, but I am pretty sure it's by design that they are negative for max and positive for min. If I switch them, they will always override the "real" values when `min()` and `max()` are called. I think that they actually should have been defined as such:

```
qnt.min <- Inf
qnt.max <- -Inf
mean.min <- Inf
mean.max <- -Inf
```

**Comment by sgoodreau** [comment]
Aha, @AdrienLeGuillou, @smjenness, I get the logic now!  We knew they were placeholders, but not why `max` was negative and `min` was positive.  Now it makes sense. I don't think there's any great need to switch to `Inf` so I'll close this issue.
