### ISSUE TITLE
clarify usability (or not) of directed networks in EpiModel (also bipartite to a lesser extent)

### ISSUE THREAD

**Issue by sgoodreau** [EpiModel/EpiModel#656]
I've always assumed that directed networks are not supported in EpiModel, as they would require a fair bit of specialized code for the epidemic modeling side of things, and I can't recall ever seeing such code or a single example being used anywhere in our materials.  But in trying to confirm this just now, I (1) never saw it mentioned explicitly in any public materials, and (2) came across the following somewhat contradictory code and documentation:

```
> ?network_initialize

network_initialize(
  n,
  directed = FALSE,
...
directed	
Logical; should edges be interpreted as directed?
...
This function is used in EpiModel workflows to initialize an empty network object with the 
directed network attribute hard set to FALSE.
```
and 
```
> aaa <- network_initialize(100, directed = TRUE)
> aaa
 Network attributes:
  vertices = 100 
  directed = TRUE 
```

So the function (which is typically the very first step in the EpiModel workflow) has an argument for `directed`, which can take either `TRUE` or `FALSE`, even if the default is `TRUE`.  The documentation then says that it is "hard set to FALSE", but the behavior suggests that it can indeed be set to `TRUE` to create a directed network.

Seems to me the overall documentation should state clearly somewhere at the high level whether or not directed networks are allowed anywhere in EpiModel.  And then the behavior of this function (and all others) should obey that rule consistently, and be documented as such.

A variation on this theme also applies to `bipartite`, in that the notes for `EpiModel 2.0` strongly emphasize that explicit bipartite functionality has gone away, but then `network_initialize` has a `bipartite` argument that can be set. 

```
> aaa <- network_initialize(100, bipartite = 50)
> aaa
 Network attributes:
  vertices = 100 
  directed = FALSE 
...
  bipartite = 50
```

**Comment by sgoodreau** [comment]
Extending this point, since `network_initialize` is an `EpiModel` function and not a `network` one, why not remove the `hyper`, `loops` and `multiple` arguments as well?  That is, remove anything that hints at the types of networks that can't actually be used in EpiModel.

**Comment by smjenness** [comment]
> So the function (which is typically the very first step in the EpiModel workflow) has an argument for directed, which can take either TRUE or FALSE, even if the default is TRUE. The documentation then says that it is "hard set to FALSE", but the behavior suggests that it can indeed be set to TRUE to create a directed network.

You're right. It is just a default, and one that can be overridden. Do you think we should just hard code it in `network_initialize`, as EpiModel is not suited for directed networks as currently designed?

Same goes for bipartite, and also for all the other weirdo network options (hyper, loops, multiple). Should `network_initialize` just always set all of these as FALSE? I think so...

**Comment by sgoodreau** [comment]
Yes, I think the beauty of creating your own `EpiModel` version of `network_initialize` is that you can make it perfectly tailored to what `EpiModel` can and can't handle.   Automatically set everything else. 

We chatted about this in our UW MIDAS weekly call, so I'm bringing in @martinamorris and @chad-klumb so they can weigh in as well.

**Comment by chad-klumb** [comment]
I'll probably make `networkLite`s error on `hyper = TRUE` or `multiple = TRUE`, while providing both `network`-style `networkLite.initialize` and `EpiModel`-style `networkLite_initialize` constructors (defaulting to `directed = TRUE` and `directed = FALSE`, respectively).

**Comment by smjenness** [comment]
@chad-klumb : could I ask you to tackle this low hanging fruit for the EpiModel v2.3 release? Let me know if you have any questions on implementation.

**Comment by chad-klumb** [comment]
Specifically, removing `directed`, `bipartite`, etc. arguments to `network_initialize`?

**Comment by smjenness** [comment]
Correct
