### ISSUE TITLE
netdx with networkLite

### ISSUE THREAD

**Issue by AdrienLeGuillou** [EpiModel/EpiModel#657]
I am updating the [BigNets](https://github.com/EpiModel/BigNets) EpiModelHIV project to work with the new `trim_netsim` function #550.

By default it converts the networks to networkLite. (`trim_netest(est, as.networkLite = TRUE)`). When doing so, the `netdx` function crashes with the following error:

```
  |Error in UseMethod("get.edge.attribute", object = x) :
  no applicable method for 'get.edge.attribute' applied to an object of class "NULL"
```

the `traceback()` puts the error inside of the `simulate` call. I can give the full traceback if needed.

The error does not occur when we de `trim_netest(est, as.networkLite = FALSE)`. 

In EpiModelHIV, the networks are converted to networkLite in the initialization module anyways so it's not an issue. My question is whether we want to allow `netdx` to work with `networkLite` and if we should set `as.networkLite = FALSE` by default on `trim_netest`. This would make sense if the workflow is as follows:

1. network estimation
2. `trim_netest`
3. network diagnostics
4. `netsim`

@smjenness @chad-klumb what do you think?

**Comment by chad-klumb** [comment]
`netdx` should work with `networkLite`s (there are tests of this in core `EpiModel`)

do you have `master` versions of all the statnet packages installed?  some updates were made to e.g. `tergm` that are not yet on `CRAN`

cf. `Remotes` in core `EpiModel`'s `DESCRIPTION` file:

```
Remotes: github::statnet/statnet.common@master,
    github::statnet/network@master,
    github::statnet/networkDynamic@master,
    github::statnet/ergm@master,
    github::statnet/tergm@master
```

**Comment by AdrienLeGuillou** [comment]
I think they were pulled when I installed `EpiModel`'s master branch.
I'll install them manually to be sure

**Comment by AdrienLeGuillou** [comment]
after installing the latest version of all the packages it now works... Sorry for that :-/

**Comment by chad-klumb** [comment]
no worries! keeping track of dependencies can be tricky :)
