### ISSUE TITLE
plot.transmat option for transmissionTimeline no longer supported

### ISSUE THREAD

**Issue by smjenness** [EpiModel/EpiModel#659]
this was in the ndtv demo of NME; was this removed from EpiModel inadvertently?

**Comment by AdrienLeGuillou** [comment]
you removed it in [this commit](https://github.com/EpiModel/EpiModel/commit/745ad46ace430bbe8334f82c22c6004c44fa26b3)

the quickest fix for NME would be to replace the call:

```r
plot(tm, style = "transmissionTimeline")
```

with

```r
ndtv::transmissionTimeline(tm)
```

**Comment by smjenness** [comment]
ah ha, can you please implement and test against NME example?

**Comment by AdrienLeGuillou** [comment]
Do you mean adding it back to EpiModel or modifying the NME example?
