### ISSUE TITLE
Rewrite type flags in plot.netdx to reduce redundancy

### ISSUE THREAD

**Issue by sgoodreau** [EpiModel/EpiModel#666]
The code for each of the three plot types (`formation`, `duration`, `dissolution`) is now much more similar than before, given that, with heterogeneous dissolution models now included, all three types are written to take either 1 or multiple stats/sub-plots. The last two in particular differ only in about 10 lines of code out of >500 (most at the start and then in a few references to `stats.table.duration` and `stats.table.dissolution`).  That means that the whole function can simply have local flags for type whenever the code differs, instead of one overall flag, reducing the 1500 lines total down to a little over 500.

**Comment by smjenness** [comment]
@sgoodreau : good find. Closing this issue because it is very close to #662.
