### ISSUE TITLE
multiple networks in netsim

### ISSUE THREAD

**Issue by DamienGeorges** [EpiModel/EpiModel#667]
Hello,

I am simulating a population with 3 partnership networks (main, short-term and one-off partnerships). So far I am using a EpiModelHIV like approach but I find it a bit heavy to maintain since I had to reimplement almost all the modules.
I was told that EpiModel now supports list of netest objects as netsim input. 

In EpiModel 1.1 (quite old but did'nt find any deprecation note) documentation I have found:

The x argument in netsim may now be a list of netest objects. This would be used only if supplying new simulation modules that know how to process that data structure. The motivation for this is to allow original models with multiple networks simulated (e.g., a main partnership network and a casual partnership network).

That being said I do not manage to use this feature. Here an attempt to code it:

```R
library(EpiModel)
nw <- network_initialize(n = 100)
nw <- set_vertex_attribute(nw, "group", rep(1:2, each = 50))
formation <- ~edges
target.stats.01 <- 50
coef.diss.01 <- dissolution_coefs(dissolution = ~offset(edges), duration = 20)
est.01 <- netest(nw, formation, target.stats.01, coef.diss.01, verbose = FALSE)
target.stats.02 <- 70
coef.diss.02 <- dissolution_coefs(dissolution = ~offset(edges), duration = 10)
est.02 <- netest(nw, formation, target.stats.02, coef.diss.02, verbose = FALSE)

# Epidemic model
param <- param.net(inf.prob = 0.3, inf.prob.g2 = 0.15)
init <- init.net(i.num = 10, i.num.g2 = 10)
control <- control.net(type = "SI", nsteps = 100, nsims = 5, verbose.int = 0)
mod1 <- netsim(list(est.01, est.02), param, init, control)
```

which returns the following error:

```R
Error: x must be either an object of class netest or class netsim
```

Does this multiple network feature really exist?
Do you have an example to share where this is multi network approach is implemented?

All the best,
Damien

Note: here is the version of the package I am using:

```R
> sessionInfo()
R version 4.1.3 (2022-03-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.3.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] EpiModel_2.2.2           statnet.common_4.6.0-381 tergm_4.0-2391          
[4] ergm_4.2-6873            networkDynamic_0.11.0    network_1.17.1-685      
[7] deSolve_1.32            
```

**Comment by AdrienLeGuillou** [comment]
Hi @DamienGeorges,

unfortunately, we the multi network feature in core EpiModel is not yet implemented. This feature is on my to-do list though and I will get back to it in the near future hopefully.

In the meantime, you can take a look at the [EpiModelCOVID repo](https://github.com/EpiModel/EpiModelCOVID) that implements simpler 3 network models. The `init_covid_corporate` function in "R/mod-init.R" and `resim_nets_covid_corporate` in "R/mod-simnet.R` should be the most relevant to you. (they work with the `main` branches of EpiModel and the Statnet packages though)

If you have questions or specific issues with it, do not hesitate to ask me and I'll answer as best I can either here or in a call if that's simpler.

I made a new issue (#669) where I'll track the work on this if you are interested in following the progress on that front

**Comment by DamienGeorges** [comment]
Thanks a lot for the quick feedback. I will stay tuned on the devel of the
multi-network feature (Happy to be a beta tester if you need some). In the
meantime I will check the EpiModelCovid19 implementation and try to update
my code accordingly. I will come back to you if needed.
All the best,
Damien

**Comment by smjenness** [comment]
I am going to close this issue because it overlaps with #669. Please follow the discussion there.
