### ISSUE TITLE
EpiModel references internal `network` data structure

### ISSUE THREAD

**Issue by chad-klumb** [EpiModel/EpiModel#671]
in net.utils.R:

https://github.com/EpiModel/EpiModel/blob/53bd16bbc5232678f7fc1c1521e40220300b68b1/R/net.utils.R#L171

https://github.com/EpiModel/EpiModel/blob/53bd16bbc5232678f7fc1c1521e40220300b68b1/R/net.utils.R#L650

https://github.com/EpiModel/EpiModel/blob/53bd16bbc5232678f7fc1c1521e40220300b68b1/R/net.utils.R#L681

https://github.com/EpiModel/EpiModel/blob/53bd16bbc5232678f7fc1c1521e40220300b68b1/R/net.utils.R#L726

This won't work for `networkLite`s, which don't have a `$val` field.

Would `list.vertex.attributes` accomplish the same goal here?

**Comment by martinamorris** [comment]
@chad-klumb does `list.vertex.attributes` already work for `networklite`s?  if so, then it seems like the right accessor function to use.  If not, then it still seems like the right accessor function to modify to do this.

**Comment by chad-klumb** [comment]
`list.vertex.attributes` is already implemented for `networkLite`s.

I wanted to confirm the intent of the code since `names(nw$val[[1]])` and `list.vertex.attributes(nw)` need not coincide for an arbitrary network `nw` (in particular, some vertex attributes may be set only for certain nodes).

**Comment by martinamorris** [comment]
> in particular, some vertex attributes may be set only for certain nodes

Are you thinking of the egocentric data context, where egos may have attributes that alters don't?  I'm having a hard time thinking of an example otherwise.

**Comment by chad-klumb** [comment]
no particular example in mind, just an observation about what the `network` class allows and how that makes the two approaches inequivalent in the general case (which may not be of concern here, which is basically what I'm asking to confirm in the op)

**Comment by martinamorris** [comment]
Ok.  I think that b/c all of these cases in the op are pulling their information from a `nw` object, not, say, from target statistics or a formula, there probably is not a use case in EpiModel for a network where attributes only apply to subsets of nodes.  Once a set of target stats and formula have been used to construct a complete network, all of the nodes will have values for all of the attributes.

But it's worth pinging @smjenness, @AdrienLeGuillou and @sgoodreau in case I'm missing something.

**Comment by sgoodreau** [comment]
Yes, allowing NAs for some nodes for some attributes is one of the many features of `network` that `EpiModel` doesn't really make use of.  Sometimes the situation happens by accident when a user forgets to write code that assigns attributes to nodes that arrive after initialization, but that's an accident.  Conceptually, it's not something that should be happening.

**Comment by smjenness** [comment]
@chad-klumb I agree with Martina's and Steve's assessments above. All nodes should have the same set of attributes in EpiModel (even if some of the values of some attributes for some/all nodes might be NA). I don't know why I didn't use `list.vertex.attributes` to pull the attribute names, but it seems like the way to go now.
