### ISSUE TITLE
formula parsing/checking in dissolution model processing

### ISSUE THREAD

**Issue by chad-klumb** [EpiModel/EpiModel#684]
Issues regarding formula handling in EpiModel came up in #508.  Three functions were mentioned:

- `netdx`
- `dissolution_coefs`
- `diss_check`

The problem in `netdx` should be resolvable by using `ergm.godfather` to determine dyad type in heterogeneous dissolution calculations.  This ensures that formulas are evaluated as they would be in `statnet` (because the evaluation happens in `statnet`).

`dissolution_coefs` just checks for `offset` and term names which can be done without getting into details of argument evaluation.  It might be a little nicer to use e.g. `list_rhs.formula` and R's `name`, `call` classes rather than strings (and maybe add more informative error messages in some cases).

As for `diss_check` I'm not aware of practically checkable necessary and sufficient conditions for (parts of) two formulas to yield the same statistics for all possible networks.  (Note that when using the "nested" EDA, we need the models to be nested not just for the initial network used in `netest` but also for all networks that could come up in `netsim`, where the network may vary from timestep to timestep in basically arbitrary ways, including changing node sets and, in particular, changing nodal attributes.)  It may be sufficient for the environments to be the same and the corresponding terms to be the same as `name`s or `call`s (after removing the `offset` decorator if present); I'll think about that a bit more, but off the top of my head I don't see a way to circumvent equivalence in that case (assuming the same `term.options` and `...` are used when initializing the models).  Those conditions are not necessary but would likely be satisfied in typical use cases.  If these checkable, sufficient conditions are not satisfied we could fall back on the non-nested EDA (perhaps giving the user an option to force the nested form if they're sure nesting is satisfied).

**Comment by smjenness** [comment]
Thanks @chad-klumb for this analysis. Look forward to discussing further with you when you get to this.

**Comment by chad-klumb** [comment]
I think this issue has been adequately addressed.  The netdx changes were made awhile ago.  The proposed diss_check changes would not be compatible with how EpiModelHIV-p currently produces dissolution formulas (which gives them different environments than the formation formulas in e.g. the EpiModelHIV-p tests), so I think those proposed changes would be more trouble than they're worth.  And the current dissolution_coefs error messages look reasonable to me.  So, overall, I think things are fine in their current state, and I'm closing this as completed.
