### ISSUE TITLE
compatible network package version

### ISSUE THREAD

**Issue by smjenness** [EpiModel/EpiModel#697]
@chad-klumb I noticed that Carter published version 1.17.2 of network on CRAN a couple days ago. Is this version compatible with your networkLite work? Rebuilding EpiModel with this CRAN version results in a change in the networkLite exports

<img width="559" alt="Screen Shot 2022-05-24 at 5 09 09 PM" src="https://user-images.githubusercontent.com/2521570/170133033-6f100be0-44d8-4531-8fe7-726a30d65062.png">

Additionally, on build there is a NOTE:

```r
Note: possible error in 'get.dyads.eids(x, el[, ': unused argument (na.omit = FALSE) at networkLite.R:569 
Note: possible error in 'get.dyads.eids(nw, el[, ': unused argument (na.omit = FALSE) at networkLite.R:607 
```

**Comment by chad-klumb** [comment]
No, I don't believe it is compatible.  I assume this is what Pavel was referring to in his email yesterday; the version of `network` pushed to CRAN does not include all the changes made since the previous release.

**Comment by smjenness** [comment]
Got it, thanks

**Comment by martinamorris** [comment]
Just to check -- is it important to get a compatible version of `network` released?

**Comment by smjenness** [comment]
yes, I am unable to push EpiModel to CRAN until this gets resolved. @martinamorris could you help push on this?

**Comment by martinamorris** [comment]
@smjenness we'll need to get Carter involved, and i'll  need a succinct summary of the changes that are needing to be pushed.  happy to chat if that's easier

**Comment by smjenness** [comment]
@martinamorris : @chad-klumb should have all the relevant details here.

**Comment by chad-klumb** [comment]
I'd recommend pushing from `master` unless there is a specific reason not to, as there are not just new generics needed by EpiModel but also some bugfixes for network itself.
