### ISSUE TITLE
stochastic test failure in main branch

### ISSUE THREAD

**Issue by chad-klumb** [EpiModel/EpiModel#698]
The following test fails stochastically in `main`:

https://github.com/EpiModel/EpiModel/blob/f912380c8f2cad280e72663d10ce090fe8ef5f29/tests/testthat/test-netdx.R#L317-L363

At a glance the issue appears to be that some dissolution dyad type edge counts will occasionally hit zero, which causes plotting issues (similar to #695).

**Comment by sgoodreau** [comment]
@chad-klumb I see you didn't assign anyone for this one or #695.  If you want to put me on it I'm happy to do so just tag me.

**Comment by chad-klumb** [comment]
Thanks I will look into this a bit and follow up next week.

**Comment by chad-klumb** [comment]
I started looking at this and #695 and I think it will be easier to fix these "well" if we first refactor the plotting code, which was already its own issue #662.  I've begun the process of refactoring in 5abdba54d4f225c40055d330bdb7ca2c0aa56088.  It will take a few more passes to get the remaining low-hanging fruit and clean up what's left; once that's done and tested we can finish addressing NA/NaN data (in what should be a relatively small number of places).

**Comment by chad-klumb** [comment]
closed by #693
