### ISSUE TITLE
merge.netsim logic inconsistent for networks and transmats

### ISSUE THREAD

**Issue by chad-klumb** [EpiModel/EpiModel#720]
We only attach `network` to the merged `netsim` object `z` if `keep.network` is `TRUE` and both `x$network` and `y$network` are not `NULL`:

https://github.com/EpiModel/EpiModel/blob/0eba8dca04ee145d7a46db634ac4c1f9fca9a3fa/R/merge.R#L233-L243

Otherwise we set `z$network <- NULL`.

The `stats$transmat` field is handled differently:

https://github.com/EpiModel/EpiModel/blob/0eba8dca04ee145d7a46db634ac4c1f9fca9a3fa/R/merge.R#L218-L230

This can result in a partially populated `stats$transmat` field in the `z` return value if `x` has `stats$transmat` and `y` was created by merging `netsim` objects with `stats$transmat` fields but `keep.transmat = FALSE` was used when constructing `y` itself.  For example

```
require(EpiModel)
nw <- network_initialize(n = 50)
est <- netest(nw, formation = ~edges,
              target.stats = c(25),
              coef.diss = dissolution_coefs(~offset(edges), 10, 0),
              verbose = FALSE)

param <- param.net(inf.prob = 0.3, act.rate = 0.5)
init <- init.net(i.num = 10)
control <- control.net(type = "SI", nsims = 1, nsteps = 50, verbose = FALSE)

mod <- netsim(est, param, init, control)

print(mod)

mod2 <- merge(mod, mod, keep.transmat = FALSE)
print(mod2)

mod3 <- merge(mod, mod2)
print(mod3)

get_transmat(mod3, sim = 1)
get_transmat(mod3, sim = 2)
get_transmat(mod3, sim = 3)
get_transmat(mod3, sim = 4)
```

errors on the last three lines, with

```
> get_transmat(mod3, sim = 2)
Error in x$stats$transmat[[sim]] : subscript out of bounds
> get_transmat(mod3, sim = 3)
Error in x$stats$transmat[[sim]] : subscript out of bounds
> get_transmat(mod3, sim = 4)
Error: Specify sim between 1 and 3
```

The final error is expected, since EpiModel checks if your index is within the range of sims performed.  The first two are a result of the transmat logic in `merge.netsim`, where `z` gets returned with a non-`NULL` `stats$transmat` field containing only the transmat for the `x` portion of the sims (i.e., sim 1).  Thus `z` (called `x` in the following code) passes all the checks in `get_transmat`

https://github.com/EpiModel/EpiModel/blob/0eba8dca04ee145d7a46db634ac4c1f9fca9a3fa/R/get.R#L173-L185

when `sim` = 2 or 3, despite not having a transmat for sims 2 or 3.

------------------

I would consider this a bug.  It could probably be fixed by handling `stats$transmat` on `z` in the same way `network` is handled: only if `keep.transmat` is `TRUE` and both `x$stats$transmat` and `y$stats$transmat` are not `NULL` should `z` get a `stats$transmat` field; otherwise `z$stats$transmat` should be set to `NULL`.

**Comment by smjenness** [comment]
@chad-klumb : thanks, that is a good find. I will merge the associated PR.
