### ISSUE TITLE
simulation naming in `get_sims` and `merge.netsim`

### ISSUE THREAD

**Issue by chad-klumb** [EpiModel/EpiModel#722]
In `merge.netsim` we rename the `y` sims to be `paste0("sim", new.range)`, while in `get_sims` we do not rename sims.  This can lead to repeated sim names, e.g.

```
require(EpiModel)
nw <- network_initialize(n = 50)
est <- netest(nw, formation = ~edges,
              target.stats = c(25),
              coef.diss = dissolution_coefs(~offset(edges), 10, 0),
              verbose = FALSE)

param <- param.net(inf.prob = 0.3, act.rate = 0.5)
init <- init.net(i.num = 10)
control <- control.net(type = "SI", nsims = 3, nsteps = 50, verbose = FALSE)

mod <- netsim(est, param, init, control)
names(mod$network)

mod13 <- get_sims(mod, c(1,3))
names(mod13$network)

mod2 <- get_sims(mod, 2)
names(mod2$network)

mod133 <- merge(mod13, mod2)
names(mod133$network)
```

produces

```
> mod <- netsim(est, param, init, control)
> names(mod$network)
[1] "sim1" "sim2" "sim3"
> 
> mod13 <- get_sims(mod, c(1,3))
> names(mod13$network)
[1] "sim1" "sim3"
> 
> mod2 <- get_sims(mod, 2)
> names(mod2$network)
[1] "sim2"
> 
> mod133 <- merge(mod13, mod2)
> names(mod133$network)
[1] "sim1" "sim3" "sim3"
```

The two `"sim3"`s in the final object are actually different sims (original sims 3 and 2, in that order).

For consistency I think we should either preserve the original names in both `get_sims` and `merge.netsim` (which could lead to repeated names) or rename to `paste0("sim",1:nsims)` in both `get_sims` and `merge.netsim`.  I favor the latter option.  Objections?

**Comment by AdrienLeGuillou** [comment]
I agree with the second option. 
Looking into the code, I am pretty sure `get_sims` and `merge.netsim` do not play well with the random parameter system and potentially with the scenarios. But that's already the case and would not be more problematic if the sims are named `paste0("sim", seq_len(nsims)`. I'll open a separate issue about it

**Comment by chad-klumb** [comment]
Okay, I'll implement the second option soon.
