### ISSUE TITLE
Remove statnet/tut repository

### ISSUE THREAD

**Issue by smjenness** [EpiModel/EpiModel#725]
@martinamorris and @mbojan: I have updated the links to all the web-based EpiModel tutorial files to hosting on the epimodel.org site directly (which gets published under the `gh-pages` branch here). So I believe you can close the github.com/statnet/tut repository. I actually do not have access to that, so I can't see what else is up there.

**Comment by smjenness** [comment]
Yes, everything has been moved over as needed.

**Comment by martinamorris** [comment]
Great, thx @smjenness.

**Comment by smjenness** [comment]
@martinamorris : is this issue closable now?

**Comment by martinamorris** [comment]
Yes -- the repo was deleted.
