### ISSUE TITLE
attach sim names to `save.other` lists?

### ISSUE THREAD

**Issue by chad-klumb** [EpiModel/EpiModel#733]
Currently we attach sim names `"sim1", "sim2", ...` to "built-in" `netsim` object fields that have one entry per sim, e.g. `network`, `stats$transmat`, etc.

We do not currently attach these sim names to `save.other` lists on the `netsim` object even though they are also structured as having one entry per sim.

Is there any reason to not add sim names in the `save.other` case?

example of current behavior:

```
require(EpiModel)
nw <- network_initialize(n = 50)
est <- netest(nw, formation = ~edges,
              target.stats = c(25),
              coef.diss = dissolution_coefs(~offset(edges), 10, 0),
              verbose = FALSE)
param <- param.net(inf.prob = 0.3, act.rate = 0.5)
init <- init.net(i.num = 10)
control <- control.net(type = "SI", nsims = 2, nsteps = 5, verbose = FALSE, 
                       save.other = c("nw"), resimulate.network = TRUE, 
                       save.network = TRUE)
mod <- netsim(est, param, init, control)
names(mod$network)
## [1] "sim1" "sim2"
names(mod$nw)
## NULL
```

**Comment by smjenness** [comment]
I don't see any reason not to add this. 

@AdrienLeGuillou what do you think?
