### ISSUE TITLE
question about transmat sim naming in saveout.R

### ISSUE THREAD

**Issue by chad-klumb** [EpiModel/EpiModel#734]
In `main` we attach sim names to some `netsim` fields here:

https://github.com/EpiModel/EpiModel/blob/90cfb6c066000b58ef1b8fd7938cdfeb297bf285/R/saveout.R#L330-L366

The `transmat` case jumps out in that the `simnames` are subset by `seq_along(out$stats$transmat)`.  Glancing at the rest of `saveout.net` it's not clear to me how this could ever be needed; if `dat$control$save.transmat == TRUE`, then `out$stats$transmat` should be a list of length equal to the number of simulations performed.  (Some entries in that list may be the trivial `data.frame()`, but they still count towards the length of the list.)

Is the `[seq_along(out$stats$transmat)]` actually needed?

**Comment by smjenness** [comment]
@AdrienLeGuillou : please provide input to this.

**Comment by AdrienLeGuillou** [comment]
I think I agree with @chad-klumb. 
This part is a remnant of some old logic that was handling `transmat` saving differently. Theoretically if `transmat == TRUE` then all simulations have one. Also, if it's not the case the code still is misleading as the Nth transmat is not necessarilly the one from the Nth simulation

**Comment by chad-klumb** [comment]
Thanks, I've opened a PR to close this issue.
