### ISSUE TITLE
trackers module should always run at end of time step

### ISSUE THREAD

**Issue by smjenness** [EpiModel/EpiModel#756]
Because `trackers.FUN` is implicitly defined, it could run in some unintended order in case there are several extension modules passed. We should always execute this module at the end of the time step, unless there is an explicit override with `module.order` in `control.net`. This default should also work automatically with EpiModel extension packages like EpiModelHIV.

**Comment by AdrienLeGuillou** [comment]
Do you think it should still be treated as a normal module where we would enforce it's `module.order` or should we go more with a `verbose.net` or `updater.net` approach where its order is hard-coded?

I tend to favor the second approach as manipulating `module.order` can be a bit more complex but both options are feasible.

**Comment by smjenness** [comment]
Fine with me to hard code (option 2). I can't imagine a situation where it would not run last. So ignore my comment above about an override with module.order. Thanks!

**Comment by AdrienLeGuillou** [comment]
fixed by #761
