### ISSUE TITLE
Standardization of nwstats initialization and updating code

### ISSUE THREAD

**Issue by smjenness** [EpiModel/EpiModel#757]
As detailed here (https://github.com/EpiModel/EpiModelHIV-p/pull/147), there has been some discrepancy in how the lists of nwstats are initialized and saved across core EpiModel and extension packages. There are different methods used if tergmLite is used, which may not be necessary. @AdrienLeGuillou additionally suggested that we could gain some efficiency if we stored all the nwstats in lists during the simulation and then bound them together at the end (i.e., in saveout.net).

 Some suggested sub-tasks:

- [ ] Review and standardize methods for initialization and updating of nwstats by core EpiModel and extension packages
- [ ] Create wrapper functions for nwstats initialization and updating that can be used across core EpiModel and extension packages. These should work for both one-layer (default) and multi-layer networks.
- [ ] Update EpiModelHIV and EpiModelCOVID with these
- [ ] In core EpiModel move the nwstats initialization from `sim_nets_t1` and into top level initialization.net function, similar to extension packages, to clarify this step.

**Comment by smjenness** [comment]
@AdrienLeGuillou Could you remind us the name of the tidyverse function to rbind lists efficiently?

**Comment by AdrienLeGuillou** [comment]
The function is `dplyr::bind_rows`

**Comment by chad-klumb** [comment]
Initialization should be extremely simple, if it is needed at all (i.e., it may be possible to write the code in such a way that a `NULL` initial value works correctly with the general one-timestep update).

To work with either one or multiple networks, producing end-of-timestep statistics, updates to nwstats will need to be obtained through `summary` calls after all the `simulate` calls and corresponding nodal attribute updates have been performed; this could be done either at the end of the network resimulation module (calling a separately defined function so as to be reusable across EpiModel and EpiModelHIV), or as a separate module called after it (with that module itself being reusable across EpiModel and EpiModelHIV).  I probably prefer the latter option; resimulation and summary are conceptually different things.

Making these changes would be much cleaner after the `simnet_updates` and `remove_deprecated` branches are merged into `main`, which could hopefully be done shortly after our next monthly meeting.

**Comment by smjenness** [comment]
Sounds great. Yes, I would like to discuss whether we need end-of-timestep stats at the next meeting.
