### ISSUE TITLE
consider removing `sim_nets_t1`

### ISSUE THREAD

**Issue by chad-klumb** [EpiModel/EpiModel#760]
IIRC this was originally introduced to facilitate the "list of networks" approach to simulating an `ergm` in `netsim` (which has since been replaced by `tergm` simulation with `networkDynamic`s).  Much of `sim_nets_t1` is redundant with `resim_nets`, and the initial `ergm` simulation (which is not redundant with `resim_nets`) could be moved into `initialize.net`.  Some small tweaks may be needed elsewhere to make this work.

Note that `sim_nets_t1` has already been removed in the `simnet_updates` branch, but we will want to discuss those changes as a whole at a later date.

An alternative to completely removing `sim_nets_t1` may be to refactor the `tergm` simulate calls so that more code can be shared between `sim_nets_t1` and `resim_nets`.

**Comment by chad-klumb** [comment]
I'm inclining more towards refactoring rather than removing `sim_nets_t1`; this may also allow more code sharing with EpiModelHIV.  Basically, starting with the `remove_deprecated` branch for simplicity, this block of code

https://github.com/EpiModel/EpiModel/blob/698f99fc9c3a255673dd9b28cdb6652f7edf6b2d/R/net.mod.simnet.R#L52-L105

would be generalized and pulled out into a separate function, taking arguments `dat, at, network, nsteps`.  (Eventually the stats part of the code would be separated into a different module per #757.)  This function could be called from `sim_nets_t1`, `resim_nets`, and any EpiModelHIV network resimulation module(s), with relatively small bits of code before/between/after calls to it.

**Comment by smjenness** [comment]
Somewhat related to #757
