### ISSUE TITLE
is it allowed to initialize a netsim run from a netsim object when `start == 1`?

### ISSUE THREAD

**Issue by chad-klumb** [EpiModel/EpiModel#764]
In `crosscheck.net` we appear to allow this in the following check:

https://github.com/EpiModel/EpiModel/blob/8755c1e2eca75c9990a1e8cb0b4588e37eeaedf6/R/net.inputs.R#L1066-L1072

but some of the code that follows in `crosscheck.net`, as well as code in `initialize.net`, appears to assume a `netest` object when `start == 1`.

**Comment by smjenness** [comment]
I believe it would be always be expected that a netest object would be used for start = 1 and a netsim object would be used for start > 1. 

@AdrienLeGuillou : any difference of opinion?

**Comment by AdrienLeGuillou** [comment]
@smjenness I agree. So far netest object are only used before the creation of `dat` at time = 1. Afterwards we either use `dat` or a netsim object in case of a restart
