### ISSUE TITLE
location of call to update_cumulative_edgelist in EpiModel vs. EpiModelHIV

### ISSUE THREAD

**Issue by chad-klumb** [EpiModel/EpiModel#767]
In core `EpiModel@main`, the function `update_cumulative_edgelist` is called in `nwupdate.net` here:

https://github.com/EpiModel/EpiModel/blob/6616af2d3f18dc466dbcbb264cb32d3d43d0b537/R/net.mod.nwupdate.R#L95-L105

In `EpiModelHIV-p@main` it is called in `simnet_msm` here:

https://github.com/EpiModel/EpiModelHIV-p/blob/e8b6f16b2bde3c7485170e0e412fd23bcac620be/R/mod.simnet.R#L113-L117

In the interest of making the core `EpiModel@multinets` module `resim_nets` re-usable by `EpiModelHIV`, it would be nice to make these consistent with each other.  Is there a reason to not put `update_cumulative_edgelist` in `resim_nets` in core `EpiModel`?

**Comment by AdrienLeGuillou** [comment]
I think it was put in `nwupdate.net` in core as all calls that has to be run after the network simulations were there. I see no reason to put it in `resim_nets`. As long as it's run after the simulation themselves all is good.
