### ISSUE TITLE
error in saveout.net upon netsim completion

### ISSUE THREAD

**Issue by ThomasKraft** [EpiModel/EpiModel#772]
Running simulations with custom modules completes all timesteps, but then errors out with message 'Error in tedgelist[, c(1L, 3L, 4L), drop = FALSE] :  subscript out of bounds'. Calling `traceback` reveals the following:

```
10: rbind(tedgelist[, c(1L, 3L, 4L), drop = FALSE], tedgelist[!tedgelist[, 
        6L], c(2L, 3L, 4L), drop = FALSE])
9: tedgelist_to_toggles(as.data.frame(dat$nw[[network]]))
8: tergm.godfather(nw ~ Passthrough(diss_formula) + EdgeAges(diss_formula) + 
       Persist(diss_formula), toggles = toggles, start = time.start - 
       1L, end = time.start + nsteps, stats.start = FALSE)
7: as.matrix(tergm.godfather(nw ~ Passthrough(diss_formula) + EdgeAges(diss_formula) + 
       Persist(diss_formula), toggles = toggles, start = time.start - 
       1L, end = time.start + nsteps, stats.start = FALSE))
6: toggles_to_diss_stats(tedgelist_to_toggles(as.data.frame(dat$nw[[network]])), 
       dat$nwparam[[network]]$coef.diss, dat$control$nsteps, dat$nw[[network]])
5: FUN(X[[i]], ...)
4: lapply(seq_len(num.nw), function(network) {
       if (dat$nwparam[[network]]$coef.diss$diss.model.type == "edgesonly") {
           toggles_to_diss_stats(tedgelist_to_toggles(as.data.frame(dat$nw[[network]])), 
               dat$nwparam[[network]]$coef.diss, dat$control$nsteps, 
               dat$nw[[network]])
       }
       else {
           NULL
       }
   })
3: saveout.net(dat_list[[s]], s)
2: process_out.net(dat_list)
1: netsim(fit_test2, param, init, control)
```

I am struggling to get the debugger to step into these functions so am having a hard time diagnosing the problem, even though it's clear that the issue arises on this line https://github.com/EpiModel/EpiModel/blob/6616af2d3f18dc466dbcbb264cb32d3d43d0b537/R/netdx.R#L439. Any advice on troubleshooting this?  I'm using current master version for EpiModel.

**Comment by chad-klumb** [comment]
Can you confirm that dat$nw is a list of networkDynamics and not ordinary networks (or networkLites)?  debug(saveout.net) should work.

**Comment by ThomasKraft** [comment]
debug(saveout.net) doesn't seem to work for me.  Probably user error, can you clarify how to use here? 

That said, if I use browser() to get as close as possible in my custom modules, then dat$nw is a list but dat$nw[[1]] is an ordinary network object, not networkDynamics.

**Comment by ThomasKraft** [comment]
Perhaps worth noting that this is a duration=1 model, but at timestep 5 I'm seeing that length(dat$nw) == 1. Shouldn't dat$nw be a list of 5 ordinary network objects at that point?

**Comment by ThomasKraft** [comment]
Yes `control$tergmLite = FALSE` in control.net.  But my impression was that I should be using `set.control.ergm` if my dissolution model specifies a duration of 1. Are you referring to `set.control.ergm` instead of `set.control.tergm` when you say that I'm running it using `network`s instead of `networkDynamics`s (or are you referring to duration =1 models more generally)?

**Comment by chad-klumb** [comment]
The list of networks approach to duration 1 models was removed awhile ago.  Both CRAN and main use `tergm` simulation to generate `networkDynamic`s in this case.

You can skip the code generating the particular error you cited in the OP by setting `control$save.diss.stats = FALSE`, but there is no guarantee that everything else will work.  I would transition to the method used by core EpiModel if you want to try and use core EpiModel functions.

**Comment by ThomasKraft** [comment]
This makes sense because my modules were built when the list of networks approach was implemented. Does this mean that referencing the network at any given step in the model is no longer done via `dat$nw[[1]]`? For example, if I wanted to modify an attribute at a given timestep, could I no longer do:

```
dat$nw[[1]] <- set_vertex_attribute(dat$nw[[1]], "attribute1", value = new_attribute)
```

Or more practically speaking, could you help me understand where my code is liable to be overriding the core EpiModel preference to generate `networkDynamic`s?

**Comment by chad-klumb** [comment]
If you're running `netsim` in core EpiModel with `tergmLite = FALSE` then after initialization `dat$nw[[1]]` will be a `networkDynamic` with the full simulation history in it.  (This should already be familiar from duration > 1 models with `tergmLite = FALSE`; it's the same now whether duration = 1 or duration > 1.)  You can get and set attributes, etc. just as you would for any other `networkDynamic`; note that if you have an open population then not all nodes need be active.

As far as where you code might be producing `network`s instead of `networkDynamic`s, I can't really say without reading/running your code.  You can see how core EpiModel handles initialization, simulation, etc. to get an idea of how to produce `networkDynamic`s in the intended fashion.

**Comment by ThomasKraft** [comment]
This is helpful, thanks.  I see that the key behavior occurs in the resim_nets function that I have a modified version of from the older codebase that used a list of static networks. Modifying that function to be in line with core EpiModel  introduces new errors ("Error in lttails[w2] <- ltheads[w2]") but at least now I know that my problems are tied to building all my modules around the older version that kept lists of static networks.

**Comment by chad-klumb** [comment]
If you have a reproducible example I can try and help isolate the problem.

**Comment by chad-klumb** [comment]
I would also note that calling `sim_nets_t1` from `initialize.net` is an important part of the network setup:

https://github.com/EpiModel/EpiModel/blob/331413420039ad4e6a9dd4a6f1989bad56053d1a/R/net.mod.init.R#L19-L36

**Comment by ThomasKraft** [comment]
I think `initialize.net` is working as expected because until my first resim_nets step the dat$nw object appears to be an appropriate list of dynamicNetworks. Trying to see if I can turn what I have into a reasonable MWE now.

**Comment by ThomasKraft** [comment]
This issue was fixed by bringing all modules in line with updated EpiModel code.
