### ISSUE TITLE
interval setting in tergm control parameters

### ISSUE THREAD

**Issue by ThomasKraft** [EpiModel/EpiModel#779]
I am having some difficulty understanding the various control parameters for `control.simulate.formula.tergm` after reading through the help files. The `MCMC.burnin` min and max parameters are straightforward, but in particular I am curious with the limited number of arguments whether there is an equivalent to `MCMC.interval` as specified for `control.simulate.formula.ergm` to change the number of proposals between sampled stats. More generally, is there a vignette or help file somewhere that can provide more information on how I might change these parameters to rectify a scenario where the number of edges is shrinking from the target over time? (I have had some success modifying the burnin parameters but these are currently requiring extremely high values that dramatically increase run time).

**Comment by chad-klumb** [comment]
The equivalent of `MCMC.interval` is the combination of the `MCMC.burnin.*` arguments.  If you simply want a specific number of proposals per time step, set both `MCMC.burnin.min` and `MCMC.burnin.max` to half of this value.

The tools we have for dealing with inefficiencies in `tergm` MCMC are the `discordance_fraction` proposal argument (passed as `MCMC.prop.args = list(discordance_fraction = [desired value])`) and the `strat` hint (passed as `MCMC.prop = ~strat([arguments to strat]) + discord + sparse`).  `discordance_fraction` should be a number in `[0,1)` and determines the fraction of proposals that are made specifically on dyads whose state has already changed in the current time step; changing its value (the default is 1/2) can improve mixing in some cases.  The `strat` hint is documented at `?InitErgmConstraint.strat`.  These may or may not help with the issues you are having; it depends on the particulars of your simulation.

Just a note that I will be out through next week so my response to anything further will be delayed.

**Comment by ThomasKraft** [comment]
Thank you these explanations are very helpful and I will try them out! If there is good further documentation on these that I have missed elsewhere please let me know.
