### ISSUE TITLE
line 373 here: EpiModel/saveout.R throws error when using nsims > 1 (2 or more)  #Error in names(out[[el.name]]) <- simnames : 'names' attribute [2] must be the same length as the vector [1]

### ISSUE THREAD

**Issue by Nimesh-Patel** [EpiModel/EpiModel#789]
Hi,
When I use EpiModelHIV library the class param_msm,control_msm,init_msm, and passed to EpiModel function netsim.
When control_msm(simno = 1,nsteps = 10, nsims=1, ncores=2)
sim <- netsim(est, params, inits, controls) 
This works fine!!! 
if I CHANGED nsims=2 (or more) ---> control_msm(simno = 1,nsteps = 10, nsims=2, ncores=2)
It throws the error
"
#Error in names(out[[el.name]]) <- simnames : 'names' attribute [2] must be the same length as the vector [1]
"
line 373 here: EpiModel/saveout.R throws error when using nsims > 1 (2 or more) 
#Error in names(out[[el.name]]) <- simnames : 'names' attribute [2] must be the same length as the vector [1]

**Comment by smjenness** [comment]
@Nimesh-Patel : could you provide a listing of all the package versions you are using. After loading `EpiModelHIV`, run: `sessioninfo::session_info()` and paste the response below.

**Comment by Nimesh-Patel** [comment]
Thank You @smjenness,
The same program works fine when I use the EpiModel version 2.2.0, The issues started when I updated from version, 2.2.0 to 2.3.1.
The saveout.net file has new addition on newer version:

if (!is.null(dat$control$save.other)) {
      for (i in seq_along(dat$control$save.other)) {
        el.name <- dat$control$save.other[i]
        names(out[[el.name]]) <- simnames
      }

Thanks,
Nimesh


- Session info ------------------------------------------------------------------------------------
 setting  value
 version  R version 4.1.3 (2022-03-10)
 os       Windows Server x64 (build 17763)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_United States.1252
 ctype    English_United States.1252
 tz       America/New_York
 date     2022-11-02
 rstudio  2022.02.1+461 Prairie Trillium (desktop)
 pandoc   2.18 @ C:\\PROGRA~3\\CHOCOL~1\\bin\\pandoc.exe

- Packages ----------------------------------------------------------------------------------------
 package        * version      date (UTC) lib source
 ape              5.6-2        2022-03-02 [1] CRAN (R 4.1.3)
 assertthat       0.2.1        2019-03-21 [2] CRAN (R 4.1.3)
 bindata          0.9-20       2021-01-29 [1] CRAN (R 4.1.3)
 cachem           1.0.6        2021-08-19 [2] CRAN (R 4.1.3)
 class            7.3-20       2022-01-16 [2] CRAN (R 4.1.3)
 cli              3.4.1        2022-09-23 [1] CRAN (R 4.1.3)
 coda             0.19-4       2020-09-30 [1] CRAN (R 4.1.3)
 codetools        0.2-18       2020-11-04 [2] CRAN (R 4.1.3)
 colorspace       2.0-3        2022-02-21 [2] CRAN (R 4.1.3)
 DBI              1.1.2        2021-12-20 [2] CRAN (R 4.1.3)
 DEoptimR         1.0-11       2022-04-03 [1] CRAN (R 4.1.3)
 deSolve        * 1.33         2022-07-16 [1] CRAN (R 4.1.3)
 doParallel       1.0.17       2022-02-07 [1] CRAN (R 4.1.3)
 dplyr            1.0.10       2022-09-01 [1] CRAN (R 4.1.3)
 e1071            1.7-11       2022-06-07 [1] CRAN (R 4.1.3)
 EpiModel       * 2.3.1        2022-10-01 [1] CRAN (R 4.1.3)
 EpiModelHIV    * 1.5.0        2022-11-01 [1] Github (statnet/EpiModelHIV@26ea27a)
 EpiModelHPC    * 2.1.2        2022-11-01 [1] Github (statnet/EpiModelHPC@091f991)
 ergm           * 4.2.3        2022-10-02 [1] CRAN (R 4.1.3)
 fansi            1.0.3        2022-03-24 [2] CRAN (R 4.1.3)
 fastmap          1.1.0        2021-01-25 [2] CRAN (R 4.1.3)
 foreach          1.5.2        2022-02-02 [2] CRAN (R 4.1.3)
 generics         0.1.3        2022-07-05 [1] CRAN (R 4.1.3)
 ggplot2          3.3.6        2022-05-03 [1] CRAN (R 4.1.3)
 glue             1.6.2        2022-02-24 [2] CRAN (R 4.1.3)
 gtable           0.3.1        2022-09-01 [1] CRAN (R 4.1.3)
 here           * 1.0.1        2020-12-13 [2] CRAN (R 4.1.3)
 iterators        1.0.14       2022-02-05 [2] CRAN (R 4.1.3)
 lattice          0.20-45      2021-09-22 [2] CRAN (R 4.1.3)
 lazyeval         0.2.2        2019-03-15 [2] CRAN (R 4.1.3)
 lifecycle        1.0.3        2022-10-07 [1] CRAN (R 4.1.3)
 lpSolveAPI       5.5.2.0-17.8 2022-08-12 [1] CRAN (R 4.1.3)
 magrittr         2.0.3        2022-03-30 [2] CRAN (R 4.1.3)
 MASS             7.3-55       2022-01-16 [2] CRAN (R 4.1.3)
 Matrix           1.4-0        2021-12-08 [2] CRAN (R 4.1.3)
 memoise          2.0.1        2021-11-26 [2] CRAN (R 4.1.3)
 munsell          0.5.0        2018-06-12 [2] CRAN (R 4.1.3)
 mvtnorm          1.1-3        2021-10-08 [2] CRAN (R 4.1.1)
 network        * 1.18.0       2022-10-06 [1] CRAN (R 4.1.3)
 networkDynamic * 0.11.2       2022-05-05 [1] CRAN (R 4.1.3)
 nlme             3.1-155      2022-01-16 [2] CRAN (R 4.1.3)
 pillar           1.8.1        2022-08-19 [1] CRAN (R 4.1.3)
 pkgconfig        2.0.3        2019-09-22 [2] CRAN (R 4.1.3)
 proxy            0.4-27       2022-06-09 [1] CRAN (R 4.1.3)
 purrr            0.3.5        2022-10-06 [1] CRAN (R 4.1.3)
 R6               2.5.1        2021-08-19 [2] CRAN (R 4.1.3)
 RColorBrewer     1.1-3        2022-04-03 [2] CRAN (R 4.1.3)
 Rcpp             1.0.9        2022-07-08 [1] CRAN (R 4.1.3)
 rlang            1.0.6        2022-09-24 [1] CRAN (R 4.1.3)
 rle              0.9.2        2020-09-25 [1] CRAN (R 4.1.3)
 robustbase       0.95-0       2022-04-02 [1] CRAN (R 4.1.3)
 rprojroot        2.0.3        2022-04-02 [2] CRAN (R 4.1.3)
 rstudioapi       0.13         2020-11-12 [2] CRAN (R 4.1.3)
 scales           1.2.1        2022-08-20 [1] CRAN (R 4.1.3)
 sessioninfo      1.2.2        2021-12-06 [2] CRAN (R 4.1.3)
 statnet.common * 4.7.0        2022-09-08 [1] CRAN (R 4.1.3)
 stringi          1.7.6        2021-11-29 [1] CRAN (R 4.1.2)
 stringr          1.4.1        2022-08-20 [1] CRAN (R 4.1.3)
 tergm          * 4.1.0        2022-06-22 [1] CRAN (R 4.1.3)
 tergmLite      * 2.6.1        2022-07-20 [1] CRAN (R 4.1.3)
 tibble           3.1.8        2022-07-22 [1] CRAN (R 4.1.3)
 tidyselect       1.2.0        2022-10-10 [1] CRAN (R 4.1.3)
 trust            0.1-8        2020-01-10 [1] CRAN (R 4.1.1)
 utf8             1.2.2        2021-07-24 [2] CRAN (R 4.1.3)
 vctrs            0.4.2        2022-09-29 [1] CRAN (R 4.1.3)

 [1] C:/Users/cva2/Documents/R/win-library/4.1
 [2] C:/Program Files/R/R-4.1.3/library
[Session_info.txt](https://github.com/EpiModel/EpiModel/files/9922414/Session_info.txt)

**Comment by AdrienLeGuillou** [comment]
Hi @Nimesh-Patel, could you paste a minimal example of the failing code so I can reproduce it on my machine?

**Comment by Nimesh-Patel** [comment]
[network_model_troubleshooting.zip](https://github.com/EpiModel/EpiModel/files/9927745/network_model_troubleshooting.zip)
Thank you Adrien, Attaching zip file of the simple code. This code works fine with EpiModel version 2.2.0 and fails on version 2.3.1.

**Comment by Nimesh-Patel** [comment]
Excellent, Thank you so much Adrien!!! 
I appreciate your help, after implementing the code, Its working fine with the newer version!!! 
Please close this ticket! Thank you again for the quick response time and finding the error.

Nimesh
