### ISSUE TITLE
Error message when runing netsim after Epimodel v2.3.1

### ISSUE THREAD

**Issue by Pie923** [EpiModel/EpiModel#793]
Hi team, hope you are doing well. I recently rerun my previous working simulation codes but unfortunately found they are not working now. I am not sure if this is because of recent updates of Epimodel and dependent packages. I have already tried to update R/Epimodel but I still got error message: Error in while (get_current_timestep(dat) < get_control(dat, "nsteps")) { : 
  argument is of length zero 

Could you please advise on this?

For reference, here is my module code: https://github.com/Pie923/Epimodel/blob/main/Epimodel_module_v1.R .  You previously kindly helped with an issue about it(issue #706 ) but it also doesn't work now . https://github.com/Pie923/Epimodel/blob/main/get_transmat_example.R  The error message is : Error in { : task 1 failed - 'argument is of length zero' 

Many thanks in advance if you could reply!

Best, 

Li

**Comment by AdrienLeGuillou** [comment]
Hi @Pie923,

[here in your new init module](https://github.com/Pie923/Epimodel/blob/main/Epimodel_module_v1.R#L26-L33) you should replace this code with `dat <- create_dat_object(param, init, control)` this new QoL function will initialize the `dat` object for you. 
Espacially in this case it initialize the `_timestep` variable that is used in `get_current_timestep`.

Tell me if that solves the whole issue.

**Comment by Pie923** [comment]
Hi @AdrienLeGuillou , thank you for your help!  Yes after replacing this line the previous error message is solved. However, I got another error message running these modules:  https://github.com/Pie923/Epimodel/blob/main/Epimodel_module_v1.R . My error message is : Error in if (dat$nwparam[[network]]$coef.diss$diss.model.type == "edgesonly") { : 
  argument is of length zero  

Could you please help locate the problem? 

Best wishes, 

Li

**Comment by AdrienLeGuillou** [comment]
The error seems to be with the `coef.diss` arguments to the networks estimations, the object created by `netest`.

Can you make me a minimal reproducible example that I could try on my machine?

**Comment by smjenness** [comment]
@Pie923 : I would suspect that the cause is an inconsistency between versions. With EpiModel and statnet packages (ergm/tergm/network/networkDynamic) updated to their latest CRAN versions, try re-estimating the network models first and then running netsim. Thanks!

**Comment by Pie923** [comment]
Hi @AdrienLeGuillou  Many thanks for your quick reply! I have checked all my packages are up-to-date but I still got this error. This is my [example code](https://github.com/Pie923/Epimodel/blob/main/example.R).  I didn't estimate a network model because I have an observed network. Unfortunately, my network data can't be shared but this error is reproducible if using data from the package networkDynamicData as in the example code.  

For reference, I also reran this [observed network example](https://github.com/EpiModel/EpiModel-Gallery/tree/main/2018-08-ObservedNetworkData) in the Epimodel Gallary and it works fine. So I'd guess that's the problem with my module codes? Thanks!

**Comment by AdrienLeGuillou** [comment]
I found the error, it is related to mandatory `nwparam` elements. 
I made [this pull request](https://github.com/Pie923/Epimodel/pull/1) to your project that fixes things.

@smjenness I opened issue #796 to discuss whether it is something that should be changed in the defaults

**Comment by Pie923** [comment]
Hi @AdrienLeGuillou  Thanks! However, after adding these 2 lines I got another error message: Error in dat$nwparam[[network]]$coef.diss$diss.model.type : 
  $ operator is invalid for atomic vectors    Any idea on how to fix this?

**Comment by AdrienLeGuillou** [comment]
my bad, I updated the PR so it works.

(most of the changes are just automatic cleanup from my editor, like removing trailing whitespaces and such)

**Comment by AdrienLeGuillou** [comment]
the main change is on line 14

**Comment by Pie923** [comment]
Thank you! This is fixed now so I am closing this issue. Have a nice day!
