### ISSUE TITLE
make a generic `get_discordant_edgelist` function

### ISSUE THREAD

**Issue by AdrienLeGuillou** [EpiModel/EpiModel#795]
This function would be a more general version of `discord_edgelist`. It would simplify models with multiple diseases as well as standardize the format of the discordant edgelist. (making it related to https://github.com/EpiModel/EpiModelHIV-p/issues/129)

I envision a function signature like:

```r
get_discordant_edgelist <- function(dat, status.attr, head.status = "i",  tail.status = "s", networks = NULL)
```

where:
- `status.attr`: the name of the attribute to use `status`, `gc.status`, etc
- `head.status`: what values on `status.attr` to look for in the "head" of the edge (default "i" for SI* models)
- `tail.status`: what values on `status.attr` to look for in the "tail" of the edge (default "s" for SI* models)
- `networks`: on what network should we look

This function can use `get_partners` by giving the `posit_ids` of the "infectious" nodes then filtering out the non "susceptible". (Conversion to `posit_ids` would be required at the end)

Similar to  `get_partners`, the output could be a `tibble`:

|head|tail|network|head_status|tail_status|
|-|-|-|-|-|

### examples

```r
# HIV on EpiModelHIV
del <- get_discordant_edgelist(dat, "status", 1, 0)

# MonkeyPox (SEIR) where only 2 networks out of 3 are of interest
del <- get_discordant_edgelist(dat, "status.mpx", "i", "s", networks = c(1, 2))

# arbitrary disease where 2 status are infectious
del <- get_discordant_edgelist(dat, "arbitrary", c("i.a", "i.b"), "s")
```

**Comment by karina-d-wallrafen** [comment]
@AdrienLeGuillou It looks like get_partners() only works if the cumulative.edgelist control setting is TRUE. Would it make more sense for get_discordant_edgelist() to use get_edgelist() (for each network) instead, so that it works even if the cumulative edgelist isn't being stored? Or is there another approach you would recommend?

**Comment by AdrienLeGuillou** [comment]
Both approaches have pros and cons:

- reusing `get_partners()` simplifies the implementation, reduce the risk of bugs  and allow for easier updating of the code if necessary. But it means that `cumulative.edgelist` is needed.
- Re-implementing from `get_edgelist` lifts the `cumulative.edgelist` requirement but means some code duplication that usually ends up in harder to debug bugs.

As we move more and more to using the `cumulative.edgelist` by default with no history (just to store the current edgelist in a cleaner format) I would lean toward this approach. Having the `cumulative.edgelist = TRUE` and `truncate.el.cuml = 0` by default would be my preference. 

However, as long as we have a  format for the `discordant.edgelist` consistent with the other edgelist like objects that's the most important in my opinion. The other part is mostly a question of ease of development and debugging (but this can lead to massive time gains in the future)
