### ISSUE TITLE
`saveout.net` requires specific elements in `dat$nwparam`

### ISSUE THREAD

**Issue by AdrienLeGuillou** [EpiModel/EpiModel#796]
related to #793 

at this line https://github.com/EpiModel/EpiModel/blob/main/R/saveout.R#L236 `saveout.net` assumes that `dat$nwparam[[network]]$coef.diss$diss.model.type` is not null. Is it something we want to enforce for all model or should we skip this part if it is `NULL`?

**Comment by smjenness** [comment]
For backwards compatibility, we can skip this if NULL.
