### ISSUE TITLE
warning when using `get_partners` 

### ISSUE THREAD

**Issue by AdrienLeGuillou** [EpiModel/EpiModel#804]
There should be a warning if the user call `get_partners`  but  `control$cumulative.edgelist` is `FALSE`

**Comment by smjenness** [comment]
This should also give a warning if the cumlative edgelist object does not directly exist on dat. This occurs if the `update_cumulative_edgelist` is not inserted within a module (e.g., https://github.com/EpiModel/EpiModelCOVID/pull/33).
