### ISSUE TITLE
make a `run` sublist in `dat` to store runtime elements

### ISSUE THREAD

**Issue by AdrienLeGuillou** [EpiModel/EpiModel#814]
we could have a `run` sublist in `dat` to contain everything that is made by `netsim` and required between timesteps.

this would include:
- `_last_uid`
- `_current_timestep`
- the positive STI diagnostic list

with this design, we could simply copy this `run` sublist in the `reinit` modules instead of having to specify each element that should be passed over on reinitialization.

This sublist could comme with accessors similar to `get/set_attr`

Note: I chose `run` to mimic the linux naming convention where /run and /var/run are folders created early at runtime to hold shared elements  

What do you think @smjenness

**Comment by smjenness** [comment]
I like it! It organizes all the common type of data elements in a logical way.

**Comment by AdrienLeGuillou** [comment]
I think I can make it work for the `window_counter` to play around the idea, then formalize it for the rest of EpiModel.

**Comment by AdrienLeGuillou** [comment]
closed with #888
