### ISSUE TITLE
consider combining basic network / dat initialization in EpiModel and EpiModelHIV-p

### ISSUE THREAD

**Issue by chad-klumb** [EpiModel/EpiModel#829]
Currently the "core" dat and network initialization is pretty similar in EpiModel@net_attr and EpiModelHIV-p@net_attr, suggesting it might be possible to combine them.  The salient difference as of now is that EpiModelHIV-p pulls `attr` from `param[["netstats"]]` whereas EpiModel pulls it from the first network object.  In the EpiModelHIV-p test example, however, the networks also have their attributes set to `attr` from `netstats`, so the EpiModel and EpiModelHIV-p approaches are really the same in that case.

Is there a reason to not pull `attr` from the first network in EpiModelHIV-p in general?  If we did so we could probably re-use a decent chunk of code from `initialize.net` in EpiModelHIV-p.

**Comment by smjenness** [comment]
@chad-klumb : I can't imagine a case where it would be problematic to pull `attr` only from the first network. I believe even in the case where some of the cross-network-degree terms are used only in one ergm (e.g., casual degree used in the main partnership ergm), the attr are still shared across networks.

**Comment by chad-klumb** [comment]
Okay, I will put together a PR for this.
