### ISSUE TITLE
interest in recording full network history in tergmLite simulations?

### ISSUE THREAD

**Issue by chad-klumb** [EpiModel/EpiModel#831]
If the full history of edge and vertex activity could be efficiently recorded in tergmLite simulations, would this be useful?

If so, are there particular analyses, visualizations, or summaries you would want from the network history?

**Comment by martinamorris** [comment]
If this could be implemented as an option, I think it would be useful.
Right off the bat, I would say that the forward and backward path
visualizations would be useful for edge activity.  I haven't done much (or
thought much) about vertex activity history.  Can you say a bit more about
what would be recorded for that?  Would it be the degree time-series?

I'm also wondering whether or how much this begins to approximate the full
networkDynamic storage.  If so, perhaps we can recycle the many, many types
of analysis that Skye built into that package.  If not, pls. let me know
what the main differences are.

thx,
mm

**Comment by chad-klumb** [comment]
Both edge and vertex activity would be binary (yes/no) records of when the edge or vertex was active in the network, probably stored as a sequence of toggle times.  Valued edges or temporally extended vertex attributes could possibly be added as extensions.

The basic data structure would store a (sorted) C++ STL `vector<int>` of toggle times for each vertex, and an `unordered_map` hashing a dyad to a (sorted) `vector<int>` of toggle times.   The dyad map could be either an `unordered_map<pair<unsigned int, unsigned int>, vector<int>>`, or an `unordered_map<unsigned int, unordered_map<unsigned int, vector<int>>>`, the former taking the dyad as a `pair<unsigned int, unsigned int>`, and the latter taking first the tail and then the head.  In the latter case, there could also be one table for in-edges and one table for out-edges, depending on what summaries, etc. are desired.  The use of a sorted `vector<int>` for toggle times should be efficient for pushing incremental changes forward in time, which is the typical use case in both `tergm` and `EpiModel`.  A different data structure for toggle times, perhaps an (ordered) `set`, might be considered if the network history is to be frequently rewritten, changing edge and/or vertex activities prior to their most recent toggle times.

This data structure would differ significantly from a `networkDynamic`, and we wouldn't be able to re-use `networkDynamic` functionality without significant modification to the `networkDynamic` package.  (The idea was to provide only the minimally necessary getters and setters to use this new data structure internally in `netsim`, and to extract basic summaries during/after the simulation.)  In principle this new data structure could be converted to a `networkDynamic` (if you wanted all the `networkDynamic` functionality), but the performance of that conversion and subsequent `networkDynamic` operations would be determined by the `networkDynamic` implementation.

Since we've prioritized other things, I won't have time to implement this.  Sam has indicated that he's satisfied with the current `cumulative_edgelist` option, so I'm closing this issue as not planned, but it will remain in the GitHub history for reference if/when someone wishes to pick this matter up again.
