### ISSUE TITLE
add delete_edges function to update.R

### ISSUE THREAD

**Issue by chad-klumb** [EpiModel/EpiModel#837]
for removing edges that include specified vertices, but not removing the vertices themselves

probably call delete_edges within delete_vertices to avoid code duplication

references EpiModel/EpiModelHIV-p#250

**Comment by smjenness** [comment]
Fine to put this in EpiModel for now, but I was wondering... would a better place for delete_vertices and delete_edges be the networkLite package?

**Comment by chad-klumb** [comment]
from email:

Since we don't store edgelists and vertex attributes as actual networkLites on the dat object, I think delete_vertices and delete_edges make more sense in the EpiModel package than in the networkLite package.
