### ISSUE TITLE
deprecate or remove deleteAttr?

### ISSUE THREAD

**Issue by chad-klumb** [EpiModel/EpiModel#846]
There are no calls to `deleteAttr` in `EpiModel/EpiModel@depart_nodes`, `EpiModel/EpiModelHIV-p@depart_nodes`, `EpiModel/EpiModelCOVID@init_nets`, or `EpiModel/EpiModel-Gallery@multinets`.  Should we deprecate or remove `deleteAttr` from core EpiModel?  As pointed out in #598 it is basically redundant with `delete_attr`.

**Comment by AdrienLeGuillou** [comment]
closed with #895
