### ISSUE TITLE
add arrive_nodes function to core EpiModel?

### ISSUE THREAD

**Issue by chad-klumb** [EpiModel/EpiModel#847]
Analogous to `depart_nodes`.  It would basically subsume the following block of code in `nwupdate`:

https://github.com/EpiModel/EpiModel/blob/f69815730adce7b1824c10f5b54df5ad85501885/R/net.mod.nwupdate.R#L42-L65

except that we wouldn't update the temporally extended disease status within the call to `arrive_nodes` (since updating the status is conceptually distinct from nodes arriving in the population).

At a glance I think the `testatus` update in the above block of code is actually redundant because we update `testatus` for all nodes further down in the same function:

https://github.com/EpiModel/EpiModel/blob/f69815730adce7b1824c10f5b54df5ad85501885/R/net.mod.nwupdate.R#L98-L107

so it seems there should be no need to do it separately for just arrivals.

**Comment by AdrienLeGuillou** [comment]
closed by #855
