### ISSUE TITLE
Remove plot.netsim (and probably elsewhere) axs argument

### ISSUE THREAD

**Issue by smjenness** [EpiModel/EpiModel#859]
This does not get processed correctly. `xaxs` and `yaxs` can still get passed through `...`, so it's unnecessary in any case.

**Comment by AdrienLeGuillou** [comment]
For `plot.netsim`, `axs` indeed has no effect but `xaxs` and `yaxs` are correctly passed to the inner call to `plot`.
Removing `axs` from `plot.netsim` is therefore trivial.

On the other hand, for `plot.dcm` and `plot.icm`, `axs` does change the axis as expected but `xaxs` and `yaxs` are not correctly passed to `plot`.

@smjenness, what do you want to do here?
1. remove `axs` from `plot.netsim`?
2. update `plot.icm` and `plot.dcm` so they behave in the same way as `plot.netsim`?
3. modify `plot.netsim` so it behaves like `plot.icm` / `plot.dcm`?

**Comment by AdrienLeGuillou** [comment]
As discussed with @smjenness 

- [ ] remove `axs` arg from `plot.netsim`, `plot.icm` and `plot.dcm`
- [ ] make the `xaxs` and `yaxs` args passable via `..` on all three functions
