### ISSUE TITLE
epiweb("net") is broken; update to use syntax invoked by changes related statnet 4.0 

### ISSUE THREAD

**Issue by sgoodreau** [EpiModel/EpiModel#860]
Trying to fit any model in it currently yields the error "NULL passed to ergm_proposal".

Replacing `ergm` and `tergm` with old versions (in my case, 3.11.0 and 3.7.0, respectively) takes away the error and returns full functionality to ``epiweb("net")``.

**Comment by sgoodreau** [comment]
Also needed to downgrade to ``EpiModel 1.7.5`` in that scenario.

**Comment by sgoodreau** [comment]
Turns out that I had the github main version of EpiModel but the CRAN master versions of the statnet packages, after having shown my students earlier in the quarter how to download the latter.  Upgrading to the main github versions for everything fixed the issue.

**Comment by smjenness** [comment]
@sgoodreau : if you don't mind, I have reopened this issue for you. Could you test your working example from your class against the current CRAN versions (specifically, ergm, tergm, and ergm.ego were updated) and the main branch of EpiModel? I ran a few models with `epiweb('net')` without a problem, but I want to make sure I'm not missing anything. Planning on releasing an EpiModel update in the next couple days. Thanks!

**Comment by sgoodreau** [comment]
Works!  Go forth and release.
