### ISSUE TITLE
time step output

### ISSUE THREAD

**Issue by danakp** [EpiModel/EpiModel#873]
Hello, I hope this finds you well.  

Is there a way to output or store each agent's status (SEIR) at each time step?

Thanks,
Dana

**Comment by AdrienLeGuillou** [comment]
Hi @danakp,
sorry for the (very) late answer.

This is possible, with a bit of work, by using the historical attributes system. This section of [the vignette](https://epimodel.github.io/EpiModel/articles/attributes-and-summary-statistics.html#historical-nodal-attributes) describes it.
