### ISSUE TITLE
Can EpiModel account for isolation (removal from network) for a set amount of time?

### ISSUE THREAD

**Issue by mxiao11** [EpiModel/EpiModel#874]
I am trying to get a model that has an isolation component; if an individual is infected, there is some percent chance that they are temporarily removed from the network for a set number of timesteps and cannot transmit the infection. However, they would still experience infection, and can re-enter the network either infected or recovered (as in, they are still subject to the infection and progression processes of the model). Is there a way to do this in EpiModel?

**Comment by AdrienLeGuillou** [comment]
Sorry for the very late response.
It is possible through various mechanisms. None are particularly easy.

- estimate the network with an `isolation` variable preventing ties and removing them. Not very practical as you would need a distribution of this variable before running epimodel

- manage it within the simulation: have an `isolation` attribute again, and use it in the various modules to exclude the individual. (e.g. remove it from sexual activity in case of HIV). Here it does not change the network itself but that could be enough

- actually remove the node from the network prior to resimulation and add it again afterwards with the same attribute just after re-simulation. Not very elegant, but that would do the trick

**Comment by smjenness** [comment]
Closing this as it was addressed by @AdrienLeGuillou
