### ISSUE TITLE
Applying scenarios to saved simulations, so they can be compared like-for-like

### ISSUE THREAD

**Issue by lgordon2019** [EpiModel/EpiModel#889]
I was wondering whether EpiModel had the capability to run from a saved set of simulations with different parameters, so that scenarios can be compared like-for-like? For example, I would like stochastic simulations A and B to be exactly the same until time point 10, when an intervention is applied and they diverge. I note that there's the capability to apply scenarios (https://cran.rstudio.com/web/packages/EpiModel/vignettes/model-parameters.html), but if the intervention is applied after time point 0, then the individual simulations will be different (due to stochasticity) even when the parameter values are the same. I would like to be able to simulate the effect of an intervention starting from exactly the same starting point.

**Comment by lgordon2019** [comment]
I'm wondering if the "resimulation" option in netsim can be used for this (e.g. if control$start > 1). I've tried to implement it by:

- Running a simulation with netsim, storing the output (a netsim object) called sim1,
- Updating control$start, control$nsteps, and running the new simulation with netsim using x = sim1 and the new control arguments

I get an error "Error: x is missing the following elements required for re-initialization: attr and temp" - What am I doing wrong?

**Comment by AdrienLeGuillou** [comment]
Hi @lgordon2019, 

`resimulation` is indeed the feature you are looking for. In order for it to work, you need to set the `save.other` argument to `control.net` to `save.other = c("attr", "temp")`. For the first simulation.

If you are using the `tergmLite = TRUE` flag as well, add `"el"` and `"net_attr`" to the list.

This will be simplified in EpiModel 2.5 (coming soonish)

**Comment by lgordon2019** [comment]
Amazing, I've got it working now - thank you!
