### ISSUE TITLE
Can netsim be used on a non-netest class object?

### ISSUE THREAD

**Issue by sfloresalvarado** [EpiModel/EpiModel#899]
Hi!

I am trying to simulate an infection that spreads in a simulated dynamic network. I have real network data, so I fitted a STERGM, then I simulated a new network from the fitted model, and I want to simulate the infection in that simulated network. The network is a Dynamic network object, which I have seen as input for netsim() in old tutorials; however, when I try to simulate I get these errors:

- "Error: x must be either an object of class netest or a list of objects of class netest when start == 1" when start == 1
- "Error: x must be a netsim object if control setting start > 1" when star > 1

Hence, I guess the object class is the problem.

Can you help me?

My code is:

```
# epidemic model ####

num_nodes <- 1e3 

## init
initial_status <- sample(c("s", "i", "r"), 
                         size = num_nodes, 
                         replace = T, 
                         prob = c(.99, .01, 0)) 

init <- init.net(status.vector = initial_status,
                 r.num = 0)

## params
param <- param.net(inf.prob = 0.1, 
                   act.rate = 0.5, 
                   rec.rate = 0.03)

## control
control <- control.net(type = "SIR", 
                       nsteps = 140, 
                       nsims = 4, 
                       ncores = 4,
                       start = 2)

sim <- netsim(x = nw, ###see details after the code                      
              param = param, 
              init = init, 
              control = control)
```

And my `nw` object has these properties:

```
NetworkDynamic properties:
  distinct change times: 135 
  maximal time range: 0 until  Inf 

 Dynamic (TEA) attributes:
  Vertex TEAs:    test.result.active 

Includes optional net.obs.period attribute:
 Network observation period info:
  Number of observation spells: 1 
  Maximal time range observed: 0 until 202 
  Temporal mode: continuous 
  Time unit: unknown 
  Suggested time increment: NA 

 Network attributes:
  vertices = 15357 
  directed = TRUE 
  hyper = FALSE 
  loops = FALSE 
  multiple = FALSE 
  bipartite = FALSE 
  net.obs.period: (not shown)
  total edges= 16620 
    missing edges= 0 
    non-missing edges= 16620 

 Vertex attribute names: 
    active edad grado sexo test.result.active vertex.names 

 Edge attribute names not shown 
```

I hope you can help me. I have been stuck here for a couple of weeks now. I really appreciate any help you can provide.

**Comment by AdrienLeGuillou** [comment]
Hi @sfloresalvarado,
`netsim` indeed requires a `netest` object, which is basically a network dynamic object with input and layout validated.

If you fitted your network yourself, the easiest way would be to re-do the estimation using the `netest` function. It's a wrapper around the `ergm` / `tergm` functions that validate the output for them to be compatible with `netsim`.

If this is not possible and you are familiar enough with R, you may want to run part of the `netest` function code to format the object properly. In `netest`, the fitting is done [at this line](https://github.com/EpiModel/EpiModel/blob/main/R/netest.R#L179), so you could in theory substitute `fit` with your model.

The first option would definitively be the easiest though. I can help with setting up the code to feed to `netest`.

**Comment by sfloresalvarado** [comment]
Thanks for your quick answer. I think it would be best if the model could be fitted using the `netest` function as it is. I would really appreciate your help with this. 

The model I have fitted is this:

```
Call:
tergm(formula = nw ~ Form(~edges + nodefactor("sexo") + nodefactor("edad") + 
    nodematch("edad")) + Persist(~edges + nodefactor("edad")), 
    estimate = "CMLE", control = control.tergm(CMLE.ergm = control.ergm(MCMC.burnin = 50000, 
        MCMC.interval = 3000, MCMC.samplesize = 6500)), times = 0:140)

Conditional Maximum Likelihood Results:

                                      Estimate Std. Error MCMC %  z value Pr(>|z|)    
Form(1)~edges                       -14.518559   0.033020      0 -439.697  < 1e-04 ***
Form(1)~nodefactor.sexo.Masculino    -0.024646   0.011907      0   -2.070 0.038472 *  
Form(1)~nodefactor.edad.[10,20)      -0.133464   0.023000      0   -5.803  < 1e-04 ***
Form(1)~nodefactor.edad.[20,30)       0.023534   0.020480      0    1.149 0.250503    
Form(1)~nodefactor.edad.[30,40)      -0.067372   0.020821      0   -3.236 0.001213 ** 
Form(1)~nodefactor.edad.[40,50)      -0.091216   0.022517      0   -4.051  < 1e-04 ***
Form(1)~nodefactor.edad.[50,60)      -0.141543   0.025337      0   -5.586  < 1e-04 ***
Form(1)~nodefactor.edad.[60,70)       0.000385   0.031415      0    0.012 0.990222    
Form(1)~nodefactor.edad.[70,80)       0.070267   0.046043      0    1.526 0.126984    
Form(1)~nodefactor.edad.[80,Inf]     -0.108730   0.073469      0   -1.480 0.138887    
Form(1)~nodematch.edad               -0.078570   0.024232      0   -3.242 0.001185 ** 
Persist(1)~edges                      1.526420   0.033599      0   45.431  < 1e-04 ***
Persist(1)~nodefactor.edad.[10,20)    0.017217   0.025358      0    0.679 0.497172    
Persist(1)~nodefactor.edad.[20,30)   -0.076005   0.022328      0   -3.404 0.000664 ***
Persist(1)~nodefactor.edad.[30,40)    0.007218   0.023028      0    0.313 0.753948    
Persist(1)~nodefactor.edad.[40,50)    0.150342   0.024987      0    6.017  < 1e-04 ***
Persist(1)~nodefactor.edad.[50,60)   -0.019260   0.027073      0   -0.711 0.476837    
Persist(1)~nodefactor.edad.[60,70)    0.039666   0.034712      0    1.143 0.253145    
Persist(1)~nodefactor.edad.[70,80)   -0.084366   0.049699      0   -1.698 0.089593 .  
Persist(1)~nodefactor.edad.[80,Inf]   0.415992   0.088152      0    4.719  < 1e-04 ***
---
```
Where `nw` is the same object I showed in my previous message (I tried netsim with that and with a simulated network from the fitted model I show here). 
 
The vignettes and tutorials I have read don't use the coefficients as they appear in the output of the fitted model but counts of observed cases per group, so I am confused about whether it is the same model or not. Also, even though the tutorials show how to use nodefactors and edges on the formulas, I haven't found how to include nodematch terms, which is essential for my model. Besides, I am unsure if I can use a persistence model or if it should necessarily be a dissolution one.

**Comment by smjenness** [comment]
Hi @sfloresalvarado : that's right, you can estimate the model with `netest`, and then pass that `netest` object directly for simulation in `netsim`. During simulation, the TERGM functions do use the coefficients as the basis for edge probabilities as a function of your model terms, but we don't directly use the coefficients during the model parameterization. The key steps are to:
1. Fit the model with `netest`. One difference in your above approach will be to use the `dissolution_coefs` function to parameterize the dissolution component of the model. This function takes as an argument the average duration of edges (for a model formula of `edges` only, or group-specific ties. I will note that this function supports more complex dissolution models like `edges + nodemix("attribute")`, but not `edges + nodefactor("attribute")`. One reason that we don't support the `nodefactor` parameterization is that edge dissolution is really a pairwise (partnership-level or relational-level) process, whereas the `nodefactor` concerns the attributes of one or both partners. Take a look at the examples and documentation for the function [here](https://epimodel.github.io/EpiModel/reference/dissolution_coefs.html). 
2. Diagnose the model with `netdx`. This will ensure that your model is fitting well to your desired data, as well as any additional terms you wish to validate on.
3. Run the epidemic model with `netsim`.

To see how the whole process works, check out [these materials ](https://epimodel.github.io/sismid/), particularly Chapters 21 and 25 to understand the parameterization workflow and how to work with attributes.

If that process does not work, you can pass in "observed" network data from an external simulation or empirical observation, and [this example from the EpiModel Gallery](https://github.com/EpiModel/EpiModel-Gallery/tree/main/2018-08-ObservedNetworkData) demonstrates how. However, it requires modifying EpiModel modules (functions that run the model) and that is a more advanced process; there are also some caveats noted here with respect to network censoring to be considered.
