### ISSUE TITLE
Problem with get_transmat() for SEIRModuleExtension.R simulation

### ISSUE THREAD

**Issue by sfloresalvarado** [EpiModel/EpiModel#900]
Hi! I have simulated a SEIR infection using `SEIRModuleExtension.R` functions. The simulation runs, and I can get most of the outputs. However, the `get_transmat()` function gives me an error.

This is my model:

```
## init
init <- init.net(i.num = num_nodes * .01)

## params
param <- param.net(inf.prob = 0.1, 
                   act.rate = 0.5, 
                   ei.rate = 0.1,
                   ir.rate = .05)

### control
control <- control.net(type = NULL, 
                       nsteps = 140, 
                       nsims = 5, 
                       infection.FUN = infect2,
                       progress.FUN = progress2,
                       ncores = parallel::detectCores())
## sim
sim <- netsim(x = netest, #tiene que ser netest
              param = param, 
              init = init, 
              control = control)
```

And when I run `get_transmat(sim)`, i get:

```
Error in `dplyr::group_by()`:
! Must group by variables found in `.data`.
Column `at` is not found.
Column `sus` is not found.
Backtrace:
 1. EpiModel::get_transmat(sim)
 4. dplyr:::group_by.data.frame(out, .data$at, .data$sus)
```

This is the traceback:

```
Error en dplyr::group_by(out, .data$at, .data$sus): 
Column `at` is not found.
Column `sus` is not found.
8. stop(fallback)
7. signal_abort(cnd, .file)
6. abort(bullets, call = error_call)
5. group_by_prepare(.data, ..., .add = .add, error_call = current_env())
4. group_by.data.frame(out, .data$at, .data$sus)
3. dplyr::group_by(out, .data$at, .data$sus)
2. dplyr::sample_n(dplyr::group_by(out, .data$at, .data$sus), 1)
1. get_transmat(sim)
```

I saw that in this year's course, you used another extension module called "mod9-SEIR-fx.R", but I couldn't find it on GitHub. I don't know if it is an issue with the function I used that you already fixed since, in section 36.5 of the course, you use it. 

I would appreciate any help you could provide on this.

**Comment by sfloresalvarado** [comment]
Hi again!

Update: I have tried this with nodes with different node numbers, attributes, network parameters, epi parameters, and the only thing that seems to be causing the problem with get_transmat() is using the SEIR module extension. Can anyone help me with this? :(

**Comment by sfloresalvarado** [comment]
I finally used the functions available [here](https://epimodel.github.io/epimodel-training/network_models_with_feedback/adding_stage_SEIR.html#the-epimodel-api) and it solved the issue.

**Comment by sfloresalvarado** [comment]
I finally used the functions available [here](https://epimodel.github.io/epimodel-training/network_models_with_feedback/adding_stage_SEIR.html#the-epimodel-api) and it solved the issue.

**Comment by AdrienLeGuillou** [comment]
Hi @sfloresalvarado, sorry I was not able to get to your question earlier. 
Glad to see you found the solution
