### ISSUE TITLE
maxchanges == Inf once dynamically allocated

### ISSUE THREAD

**Issue by AdrienLeGuillou** [EpiModel/EpiModel#904]
once https://github.com/statnet/tergm/pull/125 is merged (or equivalent). 
Set the `maxchanges` control for netsim to `inf` as we do not want to check the correctness of number of changes here. (must be done before `netsim` runs.

Related to: https://github.com/statnet/tergm/discussions/115

**Comment by smjenness** [comment]
@AdrienLeGuillou This can be closed, right?

**Comment by smjenness** [comment]
If ergm handles this dynamically now, is there any reason this has to be set to Inf? (sorry, I don't understand the internals of the change you/Pavel made)

**Comment by AdrienLeGuillou** [comment]
Yes, Pavel wanted to keep the check to avoid consuming too much RAM. 
Previously the model would allocate `maxchanges` slot in RAM at the beginning of the run and now it does the allocation dynamically but still stop if `maxchanges` changes are recorded.
By setting `maxchanges` to `Inf` we basically disregard this check and simply go with the dynamic allocation

**Comment by smjenness** [comment]
And you tested this (maxchanges == Inf) on networks of varying sizes (did you check on Billy's networks with a high density/mean degree)?

**Comment by AdrienLeGuillou** [comment]
not yet, that's on my short list of things to check

**Comment by smjenness** [comment]
Ok, so let's keep this issue open until you do that.
