### ISSUE TITLE
New ubuntu devel error

### ISSUE THREAD

**Issue by smjenness** [EpiModel/EpiModel#906]
This error about use of C function Calloc:
https://github.com/EpiModel/EpiModel/actions/runs/10796459894/job/29945513073

Is it related to this in ERGM?
https://github.com/statnet/ergm/issues/579#event-14190788101

We will probably need to fix this before we publish EpiModel v2.5.0

**Comment by AdrienLeGuillou** [comment]
It's indeed related.
It has been fixed in ergm@master: https://github.com/statnet/ergm/commit/69abee676b3b76fe430cea38d43ea9036f674d9a

**Comment by smjenness** [comment]
So we will just need to wait for Pavel to publish ergm, and then we publish EpiModel, right?

**Comment by AdrienLeGuillou** [comment]
Unless we need specific things from the next version, I am not sure we should wait for it.
Currently we work correctly against the CRAN version of ERGM.

**Comment by AdrienLeGuillou** [comment]
Unless CRAN checks would fail. 
Then yes, we need to wait for the next version

**Comment by smjenness** [comment]
Fixed with publication of ergm 4.7.0 and tergm 4.2.1
