### ISSUE TITLE
How to incorporate age-specific social contact matrices data in network models

### ISSUE THREAD

**Issue by stanleyrazor** [EpiModel/EpiModel#923]
Greetings,

I am currently working on modelling infectious diseases, and I have been using the excellent EpiModels package to do so, with network models. I would like to incorporate data for age-specific social contact matrices into the network model, such as those derived from these papers: https://doi.org/10.1371/journal.pcbi.1005697. This will enable me build networks, where the relationships (Edges) between agents(Nodes) are informed by the age-specific contacts/mixing. 

Any directions, code examples, and advices would be appreciated.

Thanks.

**Comment by AdrienLeGuillou** [comment]
Hi @stanleyrazor, 
we do something similar with EpiModelHIV. Using the data from the ARTnet study.
Here is the code for one of our network layers: https://github.com/EpiModel/EpiModelHIV-Template/blob/v3.2.x/R/A-networks/model_main.R

We use the `age.grp` attribute to do this. It's a numerical variable from 1 to 5 cutting the age.

Basically what you need to have is:
- a way to define the age groups (for us the `age.grp` attribute) 
- what relations to use. We do node factor but you could also do node.match if it suits your needs better
- targets values for the number of edges with the specified netwok statistics

You should look into the ERGM terms ref for more info about these: https://cran.r-project.org/web/packages/ergm/vignettes/ergm-term-crossRef.html

**Comment by stanleyrazor** [comment]
Thank you,
This is going to be helpful.
